// Code generated by schema-to-artifacts. DO NOT EDIT.

package usage_report_subscription

import attr "github.com/hashicorp/terraform-plugin-framework/attr"

// changeKind describes how a field transitions from state to plan.
type changeKind uint8

const (
	// changeNone means no actionable change for the field.
	changeNone changeKind = iota
	// changeUpdated means the field is set in plan and differs from state.
	changeUpdated
	// changeCleared means the field is explicitly set to null in plan.
	changeCleared
)

func (k changeKind) IsChanged() bool {
	return k != changeNone
}

func (k changeKind) IsUpdated() bool {
	return k == changeUpdated
}

func (k changeKind) IsCleared() bool {
	return k == changeCleared
}

type resourceDiff struct {
	ID                      changeKind
	S3BucketName            changeKind
	Schedule                changeKind
	LastGeneratedReportDate changeKind
	SubscriptionErrors      changeKind
}

func newResourceDiff(state resourceModel, plan resourceModel) resourceDiff {
	return resourceDiff{
		ID:                      classifyChange(state.ID, plan.ID),
		LastGeneratedReportDate: classifyChange(state.LastGeneratedReportDate, plan.LastGeneratedReportDate),
		S3BucketName:            classifyChange(state.S3BucketName, plan.S3BucketName),
		Schedule:                classifyChange(state.Schedule, plan.Schedule),
		SubscriptionErrors:      classifyChange(state.SubscriptionErrors, plan.SubscriptionErrors),
	}
}

func classifyChange(state attr.Value, plan attr.Value) changeKind {
	if plan.IsUnknown() {
		return changeNone
	}
	if state.Equal(plan) {
		return changeNone
	}
	if plan.IsNull() {
		return changeCleared
	}
	return changeUpdated
}

func (d resourceDiff) HasRemoteChanges() bool {
	return false
}

func (d resourceDiff) RequiresTagApply() bool {
	return false
}
