// Code generated by schema-to-artifacts. DO NOT EDIT.

package usage_report_subscription

import types "github.com/hashicorp/terraform-plugin-framework/types"

type resourceModel struct {
	// A synthetic identifier for the usage report subscription.
	ID types.String `tfsdk:"id"`
	// The Amazon S3 bucket where generated usage reports are stored. If on-instance session scripts and S3 logging
	// are enabled, the same bucket is reused.
	S3BucketName types.String `tfsdk:"s3_bucket_name"`
	// The schedule for generating usage reports. Currently, only `DAILY` is supported.
	Schedule types.String `tfsdk:"schedule"`
	// The time when the last usage report was generated, in RFC 3339 format.
	LastGeneratedReportDate types.String `tfsdk:"last_generated_report_date"`
	// Errors returned by AWS if usage reports could not be generated.
	SubscriptionErrors types.Set `tfsdk:"subscription_errors"`
}
type resourceModelSubscriptionErrors struct {
	// The error code returned by AWS.
	ErrorCode types.String `tfsdk:"error_code"`
	// The human-readable error message returned by AWS.
	ErrorMessage types.String `tfsdk:"error_message"`
}
