// Code generated by schema-to-artifacts. DO NOT EDIT.

package associate_user_stack

import types "github.com/hashicorp/terraform-plugin-framework/types"

type resourceModel struct {
	// A synthetic identifier for the association, composed of the stack name, authentication type, and user name.
	// This value is managed by the provider and cannot be set manually.
	ID types.String `tfsdk:"id"`
	// The name of the AppStream stack to associate with the user. Changing this value forces the association to be
	// replaced.
	StackName types.String `tfsdk:"stack_name"`
	// The email address of the AppStream user to associate with the stack. Email addresses are **case-sensitive**.
	// Changing this value forces the association to be replaced.
	UserName types.String `tfsdk:"user_name"`
	// The authentication type used by the user. Changing this value forces the association to be replaced. Valid
	// values are `API`, `SAML`, `USERPOOL`, or `AWS_AD`.
	AuthenticationType types.String `tfsdk:"authentication_type"`
	// Specifies whether a welcome email is sent to the user after the association is created. This option is only
	// applicable when `authentication_type` is `USERPOOL`. For other authentication types, the user must already
	// exist and this value is ignored. Changing this value forces the association to be replaced.
	SendEmailNotification types.Bool `tfsdk:"send_email_notification"`
}
