// Code generated by schema-to-artifacts. DO NOT EDIT.

package entitlement

import types "github.com/hashicorp/terraform-plugin-framework/types"

type dataSourceModel struct {
	// A synthetic identifier for the entitlement, composed of the stack name and entitlement name in the format
	// `<stack_name>|<name>`.
	ID types.String `tfsdk:"id"`
	// The name of the AppStream stack in which the entitlement is defined.
	StackName types.String `tfsdk:"stack_name"`
	// The name of the entitlement within the stack.
	Name types.String `tfsdk:"name"`
	// The entitlement description, if set.
	Description types.String `tfsdk:"description"`
	// Controls which applications are visible to users who match the entitlement attributes. Valid values are `ALL`
	// or `ASSOCIATED`.
	AppVisibility types.String `tfsdk:"app_visibility"`
	// The attribute rule used to match federated user attributes (AWS IAM SAML PrincipalTag). Each entitlement
	// supports **exactly one** attribute. To apply multiple rules, multiple entitlements must be created.
	Attributes types.Set `tfsdk:"attributes"`
	// The timestamp when the entitlement was created, in RFC 3339 format (for example, `2024-01-09T14:32:11Z`).
	CreatedTime types.String `tfsdk:"created_time"`
}
type dataSourceModelAttributes struct {
	// A supported AWS IAM SAML PrincipalTag attribute name. Valid values are: `roles`, `department`, `organization`,
	// `groups`, `title`, `costCenter`, `userType`.
	Name types.String `tfsdk:"name"`
	// The value of the selected attribute name that must match the federated user session.
	Value types.String `tfsdk:"value"`
}
