// Code generated by schema-to-artifacts. DO NOT EDIT.

package entitlement

import types "github.com/hashicorp/terraform-plugin-framework/types"

type resourceModel struct {
	// A synthetic identifier for the entitlement, composed of the stack name and entitlement name. This value is
	// managed by the provider and cannot be set manually.
	ID types.String `tfsdk:"id"`
	// The name of the AppStream stack in which the entitlement is defined. Changing this value forces the
	// entitlement to be replaced.
	StackName types.String `tfsdk:"stack_name"`
	// The name of the entitlement within the stack. Changing this value forces the entitlement to be replaced.
	Name types.String `tfsdk:"name"`
	// An optional description for the entitlement. Must be 256 characters or fewer.
	Description types.String `tfsdk:"description"`
	// Controls which applications are visible to users who match the entitlement attributes. Valid values are `ALL`
	// or `ASSOCIATED`.
	AppVisibility types.String `tfsdk:"app_visibility"`
	// Exactly one attribute rule used to match federated user attributes (AWS IAM SAML PrincipalTag). Each
	// entitlement supports **one** attribute only. To apply multiple rules, create multiple entitlements.
	Attributes types.Set `tfsdk:"attributes"`
	// The timestamp when the entitlement was created, in RFC 3339 format (for example, `2024-01-09T14:32:11Z`). This
	// value is set by AWS and cannot be modified.
	CreatedTime types.String `tfsdk:"created_time"`
}
type resourceModelAttributes struct {
	// A supported AWS IAM SAML PrincipalTag attribute name. Valid values are: `roles`, `department`, `organization`,
	// `groups`, `title`, `costCenter`, `userType`.
	Name types.String `tfsdk:"name"`
	// The value of the selected attribute name that must match the federated user session. Must be at least 1
	// character.
	Value types.String `tfsdk:"value"`
}
