// Code generated by schema-to-artifacts. DO NOT EDIT.

package entitlement

import attr "github.com/hashicorp/terraform-plugin-framework/attr"

// changeKind describes how a field transitions from state to plan.
type changeKind uint8

const (
	// changeNone means no actionable change for the field.
	changeNone changeKind = iota
	// changeUpdated means the field is set in plan and differs from state.
	changeUpdated
	// changeCleared means the field is explicitly set to null in plan.
	changeCleared
)

func (k changeKind) IsChanged() bool {
	return k != changeNone
}

func (k changeKind) IsUpdated() bool {
	return k == changeUpdated
}

func (k changeKind) IsCleared() bool {
	return k == changeCleared
}

type resourceDiff struct {
	ID            changeKind
	StackName     changeKind
	Name          changeKind
	Description   changeKind
	AppVisibility changeKind
	Attributes    changeKind
	CreatedTime   changeKind
}

func newResourceDiff(state resourceModel, plan resourceModel) resourceDiff {
	return resourceDiff{
		AppVisibility: classifyChange(state.AppVisibility, plan.AppVisibility),
		Attributes:    classifyChange(state.Attributes, plan.Attributes),
		CreatedTime:   classifyChange(state.CreatedTime, plan.CreatedTime),
		Description:   classifyChange(state.Description, plan.Description),
		ID:            classifyChange(state.ID, plan.ID),
		Name:          classifyChange(state.Name, plan.Name),
		StackName:     classifyChange(state.StackName, plan.StackName),
	}
}

func classifyChange(state attr.Value, plan attr.Value) changeKind {
	if plan.IsUnknown() {
		return changeNone
	}
	if state.Equal(plan) {
		return changeNone
	}
	if plan.IsNull() {
		return changeCleared
	}
	return changeUpdated
}

func (d resourceDiff) HasRemoteChanges() bool {
	return d.StackName.IsChanged() || d.Name.IsChanged() || d.Description.IsChanged() || d.AppVisibility.IsChanged() || d.Attributes.IsChanged()
}

func (d resourceDiff) RequiresTagApply() bool {
	return false
}
