// Code generated by schema-to-artifacts. DO NOT EDIT.

package directory_config

import types "github.com/hashicorp/terraform-plugin-framework/types"

type resourceModel struct {
	// A synthetic identifier for the directory config, equal to the directory name. This value is managed by the
	// provider and cannot be set manually.
	ID types.String `tfsdk:"id"`
	// The fully qualified domain name of the Microsoft Active Directory (for example, `corp.example.com`). Changing
	// this value forces the directory config to be replaced.
	DirectoryName types.String `tfsdk:"directory_name"`
	// The distinguished names of the organizational units used for computer accounts. These OUs must allow computer
	// objects to be created and managed by the AppStream service account.
	OrganizationalUnitDistinguishedNames types.Set `tfsdk:"organizational_unit_distinguished_names"`
	// Specifies the credentials of the Active Directory service account used by AppStream fleets and image builders
	// to join the domain. These credentials are write-only and are not returned by AWS after creation.
	ServiceAccountCredentials types.Object `tfsdk:"service_account_credentials"`
	// Specifies certificate-based authentication settings used to authenticate SAML 2.0 identity provider users to
	// Active Directory domain-joined streaming instances. Removing this block after it has been configured is not
	// supported by AWS update APIs. To disable certificate-based authentication, set `status` to `DISABLED`.
	CertificateBasedAuthProperties types.Object `tfsdk:"certificate_based_auth_properties"`
	// The timestamp when the directory configuration was created, in RFC 3339 format.
	CreatedTime types.String `tfsdk:"created_time"`
}
type resourceModelServiceAccountCredentials struct {
	// The user name of the Active Directory service account. This account must have permissions to create computer
	// objects, join computers to the domain, and reset passwords for computer objects in the specified
	// organizational units.
	AccountName types.String `tfsdk:"account_name"`
	// The password for the Active Directory service account. This value is sensitive, write-only, and is never
	// returned by AWS.
	AccountPassword types.String `tfsdk:"account_password"`
}
type resourceModelCertificateBasedAuthProperties struct {
	// Controls whether certificate-based authentication is enabled. Valid values are `DISABLED`, `ENABLED`, or
	// `ENABLED_NO_DIRECTORY_LOGIN_FALLBACK`. Use `DISABLED` to turn off certificate-based authentication.
	Status types.String `tfsdk:"status"`
	// The ARN of the AWS Certificate Manager Private Certificate Authority used for certificate-based
	// authentication.
	CertificateAuthorityARN types.String `tfsdk:"certificate_authority_arn"`
}
