// Code generated by schema-to-artifacts. DO NOT EDIT.

package directory_config

import attr "github.com/hashicorp/terraform-plugin-framework/attr"

// changeKind describes how a field transitions from state to plan.
type changeKind uint8

const (
	// changeNone means no actionable change for the field.
	changeNone changeKind = iota
	// changeUpdated means the field is set in plan and differs from state.
	changeUpdated
	// changeCleared means the field is explicitly set to null in plan.
	changeCleared
)

func (k changeKind) IsChanged() bool {
	return k != changeNone
}

func (k changeKind) IsUpdated() bool {
	return k == changeUpdated
}

func (k changeKind) IsCleared() bool {
	return k == changeCleared
}

type resourceDiff struct {
	ID                                   changeKind
	DirectoryName                        changeKind
	OrganizationalUnitDistinguishedNames changeKind
	ServiceAccountCredentials            changeKind
	CertificateBasedAuthProperties       changeKind
	CreatedTime                          changeKind
}

func newResourceDiff(state resourceModel, plan resourceModel) resourceDiff {
	return resourceDiff{
		CertificateBasedAuthProperties:       classifyChange(state.CertificateBasedAuthProperties, plan.CertificateBasedAuthProperties),
		CreatedTime:                          classifyChange(state.CreatedTime, plan.CreatedTime),
		DirectoryName:                        classifyChange(state.DirectoryName, plan.DirectoryName),
		ID:                                   classifyChange(state.ID, plan.ID),
		OrganizationalUnitDistinguishedNames: classifyChange(state.OrganizationalUnitDistinguishedNames, plan.OrganizationalUnitDistinguishedNames),
		ServiceAccountCredentials:            classifyChange(state.ServiceAccountCredentials, plan.ServiceAccountCredentials),
	}
}

func classifyChange(state attr.Value, plan attr.Value) changeKind {
	if plan.IsUnknown() {
		return changeNone
	}
	if state.Equal(plan) {
		return changeNone
	}
	if plan.IsNull() {
		return changeCleared
	}
	return changeUpdated
}

func (d resourceDiff) HasRemoteChanges() bool {
	return d.DirectoryName.IsChanged() || d.OrganizationalUnitDistinguishedNames.IsChanged() || d.ServiceAccountCredentials.IsChanged() || d.CertificateBasedAuthProperties.IsChanged()
}

func (d resourceDiff) RequiresTagApply() bool {
	return false
}
