version: 2
updates:
  # Maintain dependencies for Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      # Check for updates to Go modules every weekday
      interval: "daily"
    groups:
      aws-deps:
        applies-to: version-updates
        patterns:
          - "github.com/aws/*"
  - package-ecosystem: "gomod"
    directory: "/tools/provider-codegen"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/tools/commitlint"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
