// Code generated by schema-to-artifacts. DO NOT EDIT.

package image_builder

import attr "github.com/hashicorp/terraform-plugin-framework/attr"

// changeKind describes how a field transitions from state to plan.
type changeKind uint8

const (
	// changeNone means no actionable change for the field.
	changeNone changeKind = iota
	// changeUpdated means the field is set in plan and differs from state.
	changeUpdated
	// changeCleared means the field is explicitly set to null in plan.
	changeCleared
)

func (k changeKind) IsChanged() bool {
	return k != changeNone
}

func (k changeKind) IsUpdated() bool {
	return k == changeUpdated
}

func (k changeKind) IsCleared() bool {
	return k == changeCleared
}

type resourceDiff struct {
	ID                          changeKind
	Name                        changeKind
	ImageName                   changeKind
	ImageARN                    changeKind
	InstanceType                changeKind
	Description                 changeKind
	DisplayName                 changeKind
	DisableIMDSV1               changeKind
	VPCConfig                   changeKind
	IAMRoleARN                  changeKind
	EnableDefaultInternetAccess changeKind
	DomainJoinInfo              changeKind
	AppstreamAgentVersion       changeKind
	AccessEndpoints             changeKind
	RootVolumeConfig            changeKind
	Tags                        changeKind
	TagsAll                     changeKind
	ARN                         changeKind
	CreatedTime                 changeKind
	Platform                    changeKind
	NetworkAccessConfiguration  changeKind
	LatestAppstreamAgentVersion changeKind
	State                       changeKind
	StateChangeReason           changeKind
	ImageBuilderErrors          changeKind
}

func newResourceDiff(state resourceModel, plan resourceModel) resourceDiff {
	return resourceDiff{
		ARN:                         classifyChange(state.ARN, plan.ARN),
		AccessEndpoints:             classifyChange(state.AccessEndpoints, plan.AccessEndpoints),
		AppstreamAgentVersion:       classifyChange(state.AppstreamAgentVersion, plan.AppstreamAgentVersion),
		CreatedTime:                 classifyChange(state.CreatedTime, plan.CreatedTime),
		Description:                 classifyChange(state.Description, plan.Description),
		DisableIMDSV1:               classifyChange(state.DisableIMDSV1, plan.DisableIMDSV1),
		DisplayName:                 classifyChange(state.DisplayName, plan.DisplayName),
		DomainJoinInfo:              classifyChange(state.DomainJoinInfo, plan.DomainJoinInfo),
		EnableDefaultInternetAccess: classifyChange(state.EnableDefaultInternetAccess, plan.EnableDefaultInternetAccess),
		IAMRoleARN:                  classifyChange(state.IAMRoleARN, plan.IAMRoleARN),
		ID:                          classifyChange(state.ID, plan.ID),
		ImageARN:                    classifyChange(state.ImageARN, plan.ImageARN),
		ImageBuilderErrors:          classifyChange(state.ImageBuilderErrors, plan.ImageBuilderErrors),
		ImageName:                   classifyChange(state.ImageName, plan.ImageName),
		InstanceType:                classifyChange(state.InstanceType, plan.InstanceType),
		LatestAppstreamAgentVersion: classifyChange(state.LatestAppstreamAgentVersion, plan.LatestAppstreamAgentVersion),
		Name:                        classifyChange(state.Name, plan.Name),
		NetworkAccessConfiguration:  classifyChange(state.NetworkAccessConfiguration, plan.NetworkAccessConfiguration),
		Platform:                    classifyChange(state.Platform, plan.Platform),
		RootVolumeConfig:            classifyChange(state.RootVolumeConfig, plan.RootVolumeConfig),
		State:                       classifyChange(state.State, plan.State),
		StateChangeReason:           classifyChange(state.StateChangeReason, plan.StateChangeReason),
		Tags:                        classifyChange(state.Tags, plan.Tags),
		TagsAll:                     classifyChange(state.TagsAll, plan.TagsAll),
		VPCConfig:                   classifyChange(state.VPCConfig, plan.VPCConfig),
	}
}

func classifyChange(state attr.Value, plan attr.Value) changeKind {
	if plan.IsUnknown() {
		return changeNone
	}
	if state.Equal(plan) {
		return changeNone
	}
	if plan.IsNull() {
		return changeCleared
	}
	return changeUpdated
}

func (d resourceDiff) HasRemoteChanges() bool {
	return d.Name.IsChanged() || d.ImageName.IsChanged() || d.ImageARN.IsChanged() || d.InstanceType.IsChanged() || d.Description.IsChanged() || d.DisplayName.IsChanged() || d.DisableIMDSV1.IsChanged() || d.VPCConfig.IsChanged() || d.IAMRoleARN.IsChanged() || d.EnableDefaultInternetAccess.IsChanged() || d.DomainJoinInfo.IsChanged() || d.AppstreamAgentVersion.IsChanged() || d.AccessEndpoints.IsChanged() || d.RootVolumeConfig.IsChanged()
}

func (d resourceDiff) RequiresTagApply() bool {
	return d.Tags.IsChanged() || d.TagsAll.IsChanged()
}
