// Code generated by schema-to-artifacts. DO NOT EDIT.

package image_builder

import types "github.com/hashicorp/terraform-plugin-framework/types"

type resourceModel struct {
	// A synthetic identifier for the image builder, equal to the image builder name. This value is managed by the
	// provider and cannot be set manually.
	ID types.String `tfsdk:"id"`
	// The name of the AppStream image builder. Changing this value forces the image builder to be replaced.
	Name types.String `tfsdk:"name"`
	// The name of the AppStream image used to create the image builder. Either `image_name` or `image_arn` must be
	// specified.
	ImageName types.String `tfsdk:"image_name"`
	// The ARN of the AppStream image used to create the image builder. Either `image_name` or `image_arn` must be
	// specified.
	ImageARN types.String `tfsdk:"image_arn"`
	// The instance type used when launching the image builder.
	InstanceType types.String `tfsdk:"instance_type"`
	// The image builder description, if set.
	Description types.String `tfsdk:"description"`
	// The display name of the image builder shown in the AppStream user interface.
	DisplayName types.String `tfsdk:"display_name"`
	// Whether Instance Metadata Service Version 1 (IMDSv1) is disabled for the AppStream image builder. If `true`,
	// only IMDSv2 is enabled. If `false`, both IMDSv1 and IMDSv2 are enabled. The default value is `false`.
	DisableIMDSV1 types.Bool `tfsdk:"disable_imds_v1"`
	// The VPC configuration used by the image builder. Image builders use exactly one subnet.
	VPCConfig types.Object `tfsdk:"vpc_config"`
	// The ARN of the IAM role applied to the image builder.
	IAMRoleARN types.String `tfsdk:"iam_role_arn"`
	// Whether the image builder has access to the internet.
	EnableDefaultInternetAccess types.Bool `tfsdk:"enable_default_internet_access"`
	// Specifies the Active Directory domain and organizational unit used to join the image builder to a Microsoft
	// Active Directory domain.
	DomainJoinInfo types.Object `tfsdk:"domain_join_info"`
	// The desired AppStream agent version used by the image builder. Use `LATEST` to request the latest available
	// agent version.
	AppstreamAgentVersion types.String `tfsdk:"appstream_agent_version"`
	// Interface VPC endpoints through which administrators can connect to the image builder.
	AccessEndpoints types.Set `tfsdk:"access_endpoints"`
	// Specifies the root volume configuration for the image builder.
	RootVolumeConfig types.Object `tfsdk:"root_volume_config"`
	// A map of tags assigned to the image builder.
	Tags types.Map `tfsdk:"tags"`
	// A map of tags, including default tags, assigned to the image builder.
	TagsAll types.Map `tfsdk:"tags_all"`
	// The Amazon Resource Name (ARN) of the AppStream image builder.
	ARN types.String `tfsdk:"arn"`
	// The timestamp when the image builder was created, in RFC 3339 format.
	CreatedTime types.String `tfsdk:"created_time"`
	// The operating system platform of the image builder.
	Platform types.String `tfsdk:"platform"`
	// Network details of the elastic network interface attached to the image builder.
	NetworkAccessConfiguration types.Object `tfsdk:"network_access_configuration"`
	// The concrete AppStream agent version returned by AWS for the image builder. When `appstream_agent_version` is
	// set to `LATEST`, this contains the version that `LATEST` resolved to.
	ResolvedAppstreamAgentVersion types.String `tfsdk:"resolved_appstream_agent_version"`
	// Indicates whether the image builder is using the latest AppStream agent version.
	LatestAppstreamAgentVersion types.String `tfsdk:"latest_appstream_agent_version"`
	// The state of the AppStream image builder.
	State types.String `tfsdk:"state"`
	// The reason for the most recent image builder state change, if applicable.
	StateChangeReason types.Object `tfsdk:"state_change_reason"`
	// Informational list of errors reported by AWS for the image builder. These errors do not affect Terraform
	// lifecycle behavior.
	ImageBuilderErrors types.Set `tfsdk:"image_builder_errors"`
}
type resourceModelVPCConfig struct {
	// The subnet IDs in which the image builder is launched.
	SubnetIDs types.Set `tfsdk:"subnet_ids"`
	// The security group IDs associated with the image builder.
	SecurityGroupIDs types.Set `tfsdk:"security_group_ids"`
}
type resourceModelDomainJoinInfo struct {
	// The fully qualified domain name of the Active Directory.
	DirectoryName types.String `tfsdk:"directory_name"`
	// The distinguished name of the organizational unit for computer accounts.
	OrganizationalUnitDistinguishedName types.String `tfsdk:"organizational_unit_distinguished_name"`
}
type resourceModelAccessEndpoints struct {
	// The type of interface endpoint.
	EndpointType types.String `tfsdk:"endpoint_type"`
	// The identifier of the interface VPC endpoint.
	VpceID types.String `tfsdk:"vpce_id"`
}
type resourceModelRootVolumeConfig struct {
	// The size of the root volume, in GiB.
	VolumeSizeInGB types.Int32 `tfsdk:"volume_size_in_gb"`
}
type resourceModelNetworkAccessConfiguration struct {
	// The private IP address of the elastic network interface.
	EniPrivateIpAddress types.String `tfsdk:"eni_private_ip_address"`
	// The IPv6 addresses assigned to the elastic network interface.
	EniIpv6Addresses types.Set `tfsdk:"eni_ipv6_addresses"`
	// The identifier of the elastic network interface.
	EniID types.String `tfsdk:"eni_id"`
}
type resourceModelStateChangeReason struct {
	// The code describing why the image builder state changed.
	Code types.String `tfsdk:"code"`
	// The human-readable message describing the state change.
	Message types.String `tfsdk:"message"`
}
type resourceModelImageBuilderErrors struct {
	// The error code reported by AWS for the image builder.
	ErrorCode types.String `tfsdk:"error_code"`
	// The human-readable error message reported by AWS.
	ErrorMessage types.String `tfsdk:"error_message"`
	// The timestamp when the error occurred, in RFC 3339 format.
	ErrorTimestamp types.String `tfsdk:"error_timestamp"`
}
