# Visit https://golangci-lint.run/ for usage documentation
# and information on other useful linters
version: "2"
issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gofmt
    - goimports

linters:
  default: none
  enable:
    - bodyclose
    - contextcheck
    - copyloopvar
    - durationcheck
    - errcheck
    - errorlint
    - errname
    - forcetypeassert
    - gocheckcompilerdirectives
    - godot
    - gosec
    - govet
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - nolintlint
    - predeclared
    - revive
    - staticcheck
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - wastedassign
  exclusions:
    rules:
      - linters:
          - revive
        text: "var-naming: don't use an underscore in package name"
      - linters:
          - revive
        text: "var-naming: avoid package names that conflict with Go standard library package names"
      - linters:
          - revive
        path: ^internal/util/
        text: "var-naming: avoid meaningless package names"
