// Code generated by schema-to-artifacts. DO NOT EDIT.

package image_permission

import types "github.com/hashicorp/terraform-plugin-framework/types"

type dataSourceModel struct {
	// The name of the private AppStream image for which permissions are read.
	Name types.String `tfsdk:"name"`
	// The list of AWS accounts the image is shared with and their corresponding permissions.
	Permissions types.Set `tfsdk:"permissions"`
}
type dataSourceModelPermissionsImagePermissions struct {
	// Whether the image can be used to create or update AppStream fleets.
	AllowFleet types.Bool `tfsdk:"allow_fleet"`
	// Whether the image can be used to create AppStream image builders.
	AllowImageBuilder types.Bool `tfsdk:"allow_image_builder"`
}
type dataSourceModelPermissions struct {
	// The AWS account ID with which the image is shared.
	SharedAccountID types.String `tfsdk:"shared_account_id"`
	// Defines how the shared AWS account is allowed to use the image.
	ImagePermissions types.Object `tfsdk:"image_permissions"`
}
