// Code generated by schema-to-artifacts. DO NOT EDIT.

package image_permission

import types "github.com/hashicorp/terraform-plugin-framework/types"

type resourceModel struct {
	// A synthetic identifier for the image permission, composed of the image name and the shared AWS account ID.
	// This value is managed by the provider and cannot be set manually.
	ID types.String `tfsdk:"id"`
	// The name of the private AppStream image for which permissions are managed. Changing this value forces the
	// image permission to be replaced.
	Name types.String `tfsdk:"name"`
	// The 12-digit AWS account ID that is granted permissions to use the image. Each image permission resource
	// manages access for exactly one AWS account.
	SharedAccountID types.String `tfsdk:"shared_account_id"`
	// Defines how the shared AWS account is allowed to use the image. At least one permission must be enabled.
	ImagePermissions types.Object `tfsdk:"image_permissions"`
}
type resourceModelImagePermissions struct {
	// Whether the image can be used to create or update AppStream fleets in the shared AWS account.
	AllowFleet types.Bool `tfsdk:"allow_fleet"`
	// Whether the image can be used to create AppStream image builders in the shared AWS account.
	AllowImageBuilder types.Bool `tfsdk:"allow_image_builder"`
}
