// Code generated by schema-to-artifacts. DO NOT EDIT.

package app_block

import types "github.com/hashicorp/terraform-plugin-framework/types"

type dataSourceModel struct {
	// The Amazon Resource Name (ARN) of the AppStream app block.
	ID types.String `tfsdk:"id"`
	// The Amazon Resource Name (ARN) of the AppStream app block.
	ARN types.String `tfsdk:"arn"`
	// The name of the AppStream app block.
	Name types.String `tfsdk:"name"`
	// The display name of the AppStream app block, if set.
	DisplayName types.String `tfsdk:"display_name"`
	// The app block description, if set.
	Description types.String `tfsdk:"description"`
	// Specifies the Amazon S3 location that contains the app block source.
	SourceS3Location types.Object `tfsdk:"source_s3_location"`
	// Specifies the setup script used to build the app block, if present.
	SetupScriptDetails types.Object `tfsdk:"setup_script_details"`
	// Specifies the post-setup script executed after app block creation, if present.
	PostSetupScriptDetails types.Object `tfsdk:"post_setup_script_details"`
	// The packaging type of the app block.
	PackagingType types.String `tfsdk:"packaging_type"`
	// Tags assigned to the app block.
	Tags types.Map `tfsdk:"tags"`
	// The timestamp when the app block was created, in RFC 3339 format.
	CreatedTime types.String `tfsdk:"created_time"`
	// The state of the AppStream app block.
	State types.String `tfsdk:"state"`
	// Informational list of errors reported by AWS for the app block.
	AppBlockErrors types.Set `tfsdk:"app_block_errors"`
}
type dataSourceModelSourceS3Location struct {
	// The name of the Amazon S3 bucket.
	S3Bucket types.String `tfsdk:"s3_bucket"`
	// The S3 object key of the app block source, if set.
	S3Key types.String `tfsdk:"s3_key"`
}
type dataSourceModelSetupScriptDetailsScriptS3Location struct {
	// The name of the Amazon S3 bucket.
	S3Bucket types.String `tfsdk:"s3_bucket"`
	// The S3 object key of the setup script.
	S3Key types.String `tfsdk:"s3_key"`
}
type dataSourceModelSetupScriptDetails struct {
	// Specifies the Amazon S3 location of the setup script.
	ScriptS3Location types.Object `tfsdk:"script_s3_location"`
	// The run path for the setup script.
	ExecutablePath types.String `tfsdk:"executable_path"`
	// The runtime parameters passed to the setup script, if set.
	ExecutableParameters types.String `tfsdk:"executable_parameters"`
	// The maximum amount of time, in seconds, that the setup script is allowed to run.
	TimeoutInSeconds types.Int32 `tfsdk:"timeout_in_seconds"`
}
type dataSourceModelPostSetupScriptDetailsScriptS3Location struct {
	// The name of the Amazon S3 bucket.
	S3Bucket types.String `tfsdk:"s3_bucket"`
	// The S3 object key of the post-setup script.
	S3Key types.String `tfsdk:"s3_key"`
}
type dataSourceModelPostSetupScriptDetails struct {
	// Specifies the Amazon S3 location of the post-setup script.
	ScriptS3Location types.Object `tfsdk:"script_s3_location"`
	// The run path for the post-setup script.
	ExecutablePath types.String `tfsdk:"executable_path"`
	// The runtime parameters passed to the post-setup script, if set.
	ExecutableParameters types.String `tfsdk:"executable_parameters"`
	// The maximum amount of time, in seconds, that the post-setup script is allowed to run.
	TimeoutInSeconds types.Int32 `tfsdk:"timeout_in_seconds"`
}
type dataSourceModelAppBlockErrors struct {
	// The error code reported by AWS.
	ErrorCode types.String `tfsdk:"error_code"`
	// The human-readable error message reported by AWS.
	ErrorMessage types.String `tfsdk:"error_message"`
}
