// Code generated by schema-to-artifacts. DO NOT EDIT.

package app_block

import attr "github.com/hashicorp/terraform-plugin-framework/attr"

// changeKind describes how a field transitions from state to plan.
type changeKind uint8

const (
	// changeNone means no actionable change for the field.
	changeNone changeKind = iota
	// changeUpdated means the field is set in plan and differs from state.
	changeUpdated
	// changeCleared means the field is explicitly set to null in plan.
	changeCleared
)

func (k changeKind) IsChanged() bool {
	return k != changeNone
}

func (k changeKind) IsUpdated() bool {
	return k == changeUpdated
}

func (k changeKind) IsCleared() bool {
	return k == changeCleared
}

type resourceDiff struct {
	ID                     changeKind
	Name                   changeKind
	DisplayName            changeKind
	Description            changeKind
	SourceS3Location       changeKind
	SetupScriptDetails     changeKind
	PostSetupScriptDetails changeKind
	PackagingType          changeKind
	Tags                   changeKind
	TagsAll                changeKind
	ARN                    changeKind
	CreatedTime            changeKind
	State                  changeKind
	AppBlockErrors         changeKind
}

func newResourceDiff(state resourceModel, plan resourceModel) resourceDiff {
	return resourceDiff{
		ARN:                    classifyChange(state.ARN, plan.ARN),
		AppBlockErrors:         classifyChange(state.AppBlockErrors, plan.AppBlockErrors),
		CreatedTime:            classifyChange(state.CreatedTime, plan.CreatedTime),
		Description:            classifyChange(state.Description, plan.Description),
		DisplayName:            classifyChange(state.DisplayName, plan.DisplayName),
		ID:                     classifyChange(state.ID, plan.ID),
		Name:                   classifyChange(state.Name, plan.Name),
		PackagingType:          classifyChange(state.PackagingType, plan.PackagingType),
		PostSetupScriptDetails: classifyChange(state.PostSetupScriptDetails, plan.PostSetupScriptDetails),
		SetupScriptDetails:     classifyChange(state.SetupScriptDetails, plan.SetupScriptDetails),
		SourceS3Location:       classifyChange(state.SourceS3Location, plan.SourceS3Location),
		State:                  classifyChange(state.State, plan.State),
		Tags:                   classifyChange(state.Tags, plan.Tags),
		TagsAll:                classifyChange(state.TagsAll, plan.TagsAll),
	}
}

func classifyChange(state attr.Value, plan attr.Value) changeKind {
	if plan.IsUnknown() {
		return changeNone
	}
	if state.Equal(plan) {
		return changeNone
	}
	if plan.IsNull() {
		return changeCleared
	}
	return changeUpdated
}

func (d resourceDiff) HasRemoteChanges() bool {
	return d.Name.IsChanged() || d.DisplayName.IsChanged() || d.Description.IsChanged() || d.SourceS3Location.IsChanged() || d.SetupScriptDetails.IsChanged() || d.PostSetupScriptDetails.IsChanged() || d.PackagingType.IsChanged()
}

func (d resourceDiff) RequiresTagApply() bool {
	return d.Tags.IsChanged() || d.TagsAll.IsChanged()
}
