// Code generated by schema-to-artifacts. DO NOT EDIT.

package app_block

import types "github.com/hashicorp/terraform-plugin-framework/types"

type resourceModel struct {
	// The Amazon Resource Name (ARN) of the AppStream app block. This value is managed by the provider and cannot be
	// set manually.
	ID types.String `tfsdk:"id"`
	// The name of the AppStream app block. Changing this value forces the app block to be replaced.
	Name types.String `tfsdk:"name"`
	// The display name of the AppStream app block.
	DisplayName types.String `tfsdk:"display_name"`
	// The AppStream app block description, if set. Must be 256 characters or fewer.
	Description types.String `tfsdk:"description"`
	// Specifies the Amazon S3 location that contains the app block source. Depending on the packaging type, this can
	// be an application package (VHD) or source content used to build the app block.
	SourceS3Location types.Object `tfsdk:"source_s3_location"`
	// Specifies the setup script that is executed when the app block is built. This configuration is required for
	// app blocks with the `CUSTOM` packaging type.
	SetupScriptDetails types.Object `tfsdk:"setup_script_details"`
	// Specifies a post-setup script that is executed after the app block is created. This configuration is supported
	// only for app blocks with the `APPSTREAM2` packaging type.
	PostSetupScriptDetails types.Object `tfsdk:"post_setup_script_details"`
	// The packaging type of the app block. Valid values are `CUSTOM` or `APPSTREAM2`.
	PackagingType types.String `tfsdk:"packaging_type"`
	// A map of tags assigned to the app block.
	Tags types.Map `tfsdk:"tags"`
	// A map of tags, including default tags, assigned to the app block.
	TagsAll types.Map `tfsdk:"tags_all"`
	// The Amazon Resource Name (ARN) of the app block.
	ARN types.String `tfsdk:"arn"`
	// The timestamp when the app block was created, in RFC 3339 format.
	CreatedTime types.String `tfsdk:"created_time"`
	// The state of the AppStream app block.
	State types.String `tfsdk:"state"`
	// Informational list of errors reported by AWS for the app block. These errors do not affect Terraform lifecycle
	// behavior.
	AppBlockErrors types.Set `tfsdk:"app_block_errors"`
}
type resourceModelSourceS3Location struct {
	// The name of the Amazon S3 bucket.
	S3Bucket types.String `tfsdk:"s3_bucket"`
	// The S3 object key of the app block source.
	S3Key types.String `tfsdk:"s3_key"`
}
type resourceModelSetupScriptDetailsScriptS3Location struct {
	// The name of the Amazon S3 bucket.
	S3Bucket types.String `tfsdk:"s3_bucket"`
	// The S3 object key of the setup script.
	S3Key types.String `tfsdk:"s3_key"`
}
type resourceModelSetupScriptDetails struct {
	// Specifies the Amazon S3 location of the setup script.
	ScriptS3Location types.Object `tfsdk:"script_s3_location"`
	// The run path for the setup script.
	ExecutablePath types.String `tfsdk:"executable_path"`
	// The runtime parameters passed to the setup script.
	ExecutableParameters types.String `tfsdk:"executable_parameters"`
	// The maximum amount of time, in seconds, that the setup script is allowed to run.
	TimeoutInSeconds types.Int32 `tfsdk:"timeout_in_seconds"`
}
type resourceModelPostSetupScriptDetailsScriptS3Location struct {
	// The name of the Amazon S3 bucket.
	S3Bucket types.String `tfsdk:"s3_bucket"`
	// The S3 object key of the post-setup script.
	S3Key types.String `tfsdk:"s3_key"`
}
type resourceModelPostSetupScriptDetails struct {
	// Specifies the Amazon S3 location of the post-setup script.
	ScriptS3Location types.Object `tfsdk:"script_s3_location"`
	// The run path for the post-setup script.
	ExecutablePath types.String `tfsdk:"executable_path"`
	// The runtime parameters passed to the post-setup script.
	ExecutableParameters types.String `tfsdk:"executable_parameters"`
	// The maximum amount of time, in seconds, that the post-setup script is allowed to run.
	TimeoutInSeconds types.Int32 `tfsdk:"timeout_in_seconds"`
}
type resourceModelAppBlockErrors struct {
	// The error code reported by AWS for the app block.
	ErrorCode types.String `tfsdk:"error_code"`
	// The human-readable error message reported by AWS.
	ErrorMessage types.String `tfsdk:"error_message"`
}
