// Code generated by schema-to-artifacts. DO NOT EDIT.

package software_associations

import types "github.com/hashicorp/terraform-plugin-framework/types"

type dataSourceModel struct {
	// The ARN of the AppStream image or image builder for which software associations are read.
	AssociatedResource types.String `tfsdk:"associated_resource"`
	// The list of license-included software applications associated with the resource and their deployment status.
	SoftwareAssociations types.Set `tfsdk:"software_associations"`
}
type dataSourceModelSoftwareAssociationsDeploymentErrors struct {
	// The error code reported by AWS for the software association.
	ErrorCode types.String `tfsdk:"error_code"`
	// The human-readable error message reported by AWS for the software association.
	ErrorMessage types.String `tfsdk:"error_message"`
}
type dataSourceModelSoftwareAssociations struct {
	// The name of the license-included application associated with the resource.
	SoftwareName types.String `tfsdk:"software_name"`
	// The deployment status of the license-included application, as reported by AWS.
	Status types.String `tfsdk:"status"`
	// Informational list of error details for failed software deployments. These errors are reported by AWS and do
	// not affect Terraform lifecycle behavior.
	DeploymentErrors types.Set `tfsdk:"deployment_errors"`
}
