// Code generated by schema-to-artifacts. DO NOT EDIT.

package export_image_tasks

import types "github.com/hashicorp/terraform-plugin-framework/types"

type dataSourceModel struct {
	// Optional filters to narrow down the list of export image tasks. Filters allow selecting tasks by attributes
	// such as state or creation date.
	Filters types.Set `tfsdk:"filters"`
	// The list of export image tasks that match the specified filters.
	ExportImageTasks types.Set `tfsdk:"export_image_tasks"`
}
type dataSourceModelFilters struct {
	// The name of the filter to apply.
	Name types.String `tfsdk:"name"`
	// One or more values for the specified filter name.
	Values types.Set `tfsdk:"values"`
}
type dataSourceModelExportImageTasksErrorDetails struct {
	// The error code reported by AWS.
	ErrorCode types.String `tfsdk:"error_code"`
	// The human-readable error message reported by AWS.
	ErrorMessage types.String `tfsdk:"error_message"`
}
type dataSourceModelExportImageTasks struct {
	// The unique identifier of the export image task.
	TaskID types.String `tfsdk:"task_id"`
	// The Amazon Resource Name (ARN) of the AppStream Applications image being exported.
	ImageARN types.String `tfsdk:"image_arn"`
	// The name of the EC2 AMI created by the export image task.
	AmiName types.String `tfsdk:"ami_name"`
	// The description applied to the exported EC2 AMI, if set.
	AmiDescription types.String `tfsdk:"ami_description"`
	// The ID of the EC2 AMI created by the export image task. This attribute is only populated when the task
	// completes successfully.
	AmiID types.String `tfsdk:"ami_id"`
	// The current state of the export image task. Valid values are `EXPORTING`, `COMPLETED`, or `FAILED`.
	State types.String `tfsdk:"state"`
	// The timestamp when the export image task was created, in RFC 3339 format.
	CreatedDate types.String `tfsdk:"created_date"`
	// The tags applied to the exported EC2 AMI.
	TagSpecifications types.Map `tfsdk:"tag_specifications"`
	// Details about errors that occurred during the export process. This attribute is only populated when the task
	// state is `FAILED`.
	ErrorDetails types.Set `tfsdk:"error_details"`
}
