// Code generated by schema-to-artifacts. DO NOT EDIT.

package associate_app_block_builder_app_block

import attr "github.com/hashicorp/terraform-plugin-framework/attr"

// changeKind describes how a field transitions from state to plan.
type changeKind uint8

const (
	// changeNone means no actionable change for the field.
	changeNone changeKind = iota
	// changeUpdated means the field is set in plan and differs from state.
	changeUpdated
	// changeCleared means the field is explicitly set to null in plan.
	changeCleared
)

func (k changeKind) IsChanged() bool {
	return k != changeNone
}

func (k changeKind) IsUpdated() bool {
	return k == changeUpdated
}

func (k changeKind) IsCleared() bool {
	return k == changeCleared
}

type resourceDiff struct {
	ID                  changeKind
	AppBlockBuilderName changeKind
	AppBlockARN         changeKind
}

func newResourceDiff(state resourceModel, plan resourceModel) resourceDiff {
	return resourceDiff{
		AppBlockARN:         classifyChange(state.AppBlockARN, plan.AppBlockARN),
		AppBlockBuilderName: classifyChange(state.AppBlockBuilderName, plan.AppBlockBuilderName),
		ID:                  classifyChange(state.ID, plan.ID),
	}
}

func classifyChange(state attr.Value, plan attr.Value) changeKind {
	if plan.IsUnknown() {
		return changeNone
	}
	if state.Equal(plan) {
		return changeNone
	}
	if plan.IsNull() {
		return changeCleared
	}
	return changeUpdated
}

func (d resourceDiff) HasRemoteChanges() bool {
	return d.AppBlockBuilderName.IsChanged() || d.AppBlockARN.IsChanged()
}

func (d resourceDiff) RequiresTagApply() bool {
	return false
}
