// Code generated by schema-to-artifacts. DO NOT EDIT.

package associate_app_block_builder_app_block

import types "github.com/hashicorp/terraform-plugin-framework/types"

type resourceModel struct {
	// A synthetic identifier for the association, composed of the app block builder name and app block ARN. This
	// value is managed by the provider and cannot be set manually.
	ID types.String `tfsdk:"id"`
	// The name of the AppStream app block builder to associate with the app block. Changing this value forces the
	// association to be replaced.
	AppBlockBuilderName types.String `tfsdk:"app_block_builder_name"`
	// The ARN of the AppStream app block to associate with the app block builder. Changing this value forces the
	// association to be replaced.
	AppBlockARN types.String `tfsdk:"app_block_arn"`
}
