// Code generated by schema-to-artifacts. DO NOT EDIT.

package stack

import types "github.com/hashicorp/terraform-plugin-framework/types"

type dataSourceModel struct {
	// A synthetic identifier for the stack, equal to the stack name.
	ID types.String `tfsdk:"id"`
	// The name of the AppStream stack to read.
	Name types.String `tfsdk:"name"`
	// The stack description, if set.
	Description types.String `tfsdk:"description"`
	// The name displayed to users in the AppStream user interface.
	DisplayName types.String `tfsdk:"display_name"`
	// Storage connectors that are enabled for the stack.
	StorageConnectors types.Set `tfsdk:"storage_connectors"`
	// The URL users are redirected to after their AppStream streaming session ends.
	RedirectURL types.String `tfsdk:"redirect_url"`
	// The URL users are redirected to after clicking the **Send Feedback** link.
	FeedbackURL types.String `tfsdk:"feedback_url"`
	// Actions that are enabled or disabled for users during streaming sessions.
	UserSettings types.Set `tfsdk:"user_settings"`
	// Application settings persistence configuration for the stack.
	ApplicationSettings types.Object `tfsdk:"application_settings"`
	// URL redirection settings configured for the stack.
	ContentRedirection types.Object `tfsdk:"content_redirection"`
	// Tags assigned to the stack.
	Tags types.Map `tfsdk:"tags"`
	// Interface VPC endpoints through which users can connect to the stack.
	AccessEndpoints types.Set `tfsdk:"access_endpoints"`
	// Domains where streaming sessions can be embedded in an iframe.
	EmbedHostDomains types.Set `tfsdk:"embed_host_domains"`
	// Preferred streaming protocol configuration for the stack.
	StreamingExperienceSettings types.Object `tfsdk:"streaming_experience_settings"`
	// The Amazon Resource Name (ARN) of the AppStream stack.
	ARN types.String `tfsdk:"arn"`
	// The timestamp when the stack was created, in RFC 3339 format.
	CreatedTime types.String `tfsdk:"created_time"`
	// Informational list of errors reported by AWS for the stack.
	StackErrors types.Set `tfsdk:"stack_errors"`
}
type dataSourceModelStorageConnectors struct {
	// The type of storage connector.
	ConnectorType types.String `tfsdk:"connector_type"`
	// The resource identifier associated with the storage connector.
	ResourceIdentifier types.String `tfsdk:"resource_identifier"`
	// The domain names associated with the storage connector.
	Domains types.Set `tfsdk:"domains"`
	// The domain names that require administrator consent.
	DomainsRequireAdminConsent types.Set `tfsdk:"domains_require_admin_consent"`
}
type dataSourceModelUserSettings struct {
	// The user action.
	Action types.String `tfsdk:"action"`
	// Whether the action is enabled or disabled.
	Permission types.String `tfsdk:"permission"`
	// The maximum number of characters that can be copied for clipboard actions.
	MaximumLength types.Int32 `tfsdk:"maximum_length"`
}
type dataSourceModelApplicationSettings struct {
	// Whether application settings persistence is enabled.
	Enabled types.Bool `tfsdk:"enabled"`
	// The name of the application settings group.
	SettingsGroup types.String `tfsdk:"settings_group"`
	// The S3 bucket name where users persistent application settings are stored.
	S3BucketName types.String `tfsdk:"s3_bucket_name"`
}
type dataSourceModelContentRedirectionHostToClient struct {
	// Whether URLs opened in the remote AppStream session are redirected to the local client browser.
	Enabled types.Bool `tfsdk:"enabled"`
	// A set of URL patterns that are allowed to be redirected to the local client browser.
	AllowedUrls types.Set `tfsdk:"allowed_urls"`
	// A set of URL patterns that are denied from redirection. Denied patterns take precedence over allowed patterns.
	DeniedUrls types.Set `tfsdk:"denied_urls"`
}
type dataSourceModelContentRedirection struct {
	// URL redirection settings for URLs opened in the remote AppStream session and redirected to the local client
	// browser.
	HostToClient types.Object `tfsdk:"host_to_client"`
}
type dataSourceModelAccessEndpoints struct {
	// The type of interface endpoint.
	EndpointType types.String `tfsdk:"endpoint_type"`
	// The identifier of the interface VPC endpoint.
	VpceID types.String `tfsdk:"vpce_id"`
}
type dataSourceModelStreamingExperienceSettings struct {
	// The preferred streaming protocol for the stack.
	PreferredProtocol types.String `tfsdk:"preferred_protocol"`
}
type dataSourceModelStackErrors struct {
	// The error code reported by AWS.
	ErrorCode types.String `tfsdk:"error_code"`
	// The human-readable error message reported by AWS.
	ErrorMessage types.String `tfsdk:"error_message"`
}
