// Code generated by schema-to-artifacts. DO NOT EDIT.

package stack

import attr "github.com/hashicorp/terraform-plugin-framework/attr"

// changeKind describes how a field transitions from state to plan.
type changeKind uint8

const (
	// changeNone means no actionable change for the field.
	changeNone changeKind = iota
	// changeUpdated means the field is set in plan and differs from state.
	changeUpdated
	// changeCleared means the field is explicitly set to null in plan.
	changeCleared
)

func (k changeKind) IsChanged() bool {
	return k != changeNone
}

func (k changeKind) IsUpdated() bool {
	return k == changeUpdated
}

func (k changeKind) IsCleared() bool {
	return k == changeCleared
}

type resourceDiff struct {
	ID                          changeKind
	Name                        changeKind
	Description                 changeKind
	DisplayName                 changeKind
	StorageConnectors           changeKind
	RedirectUrl                 changeKind
	FeedbackUrl                 changeKind
	UserSettings                changeKind
	ApplicationSettings         changeKind
	AccessEndpoints             changeKind
	EmbedHostDomains            changeKind
	StreamingExperienceSettings changeKind
	Tags                        changeKind
	TagsAll                     changeKind
	ARN                         changeKind
	CreatedTime                 changeKind
	StackErrors                 changeKind
}

func newResourceDiff(state resourceModel, plan resourceModel) resourceDiff {
	return resourceDiff{
		ARN:                         classifyChange(state.ARN, plan.ARN),
		AccessEndpoints:             classifyChange(state.AccessEndpoints, plan.AccessEndpoints),
		ApplicationSettings:         classifyChange(state.ApplicationSettings, plan.ApplicationSettings),
		CreatedTime:                 classifyChange(state.CreatedTime, plan.CreatedTime),
		Description:                 classifyChange(state.Description, plan.Description),
		DisplayName:                 classifyChange(state.DisplayName, plan.DisplayName),
		EmbedHostDomains:            classifyChange(state.EmbedHostDomains, plan.EmbedHostDomains),
		FeedbackUrl:                 classifyChange(state.FeedbackUrl, plan.FeedbackUrl),
		ID:                          classifyChange(state.ID, plan.ID),
		Name:                        classifyChange(state.Name, plan.Name),
		RedirectUrl:                 classifyChange(state.RedirectUrl, plan.RedirectUrl),
		StackErrors:                 classifyChange(state.StackErrors, plan.StackErrors),
		StorageConnectors:           classifyChange(state.StorageConnectors, plan.StorageConnectors),
		StreamingExperienceSettings: classifyChange(state.StreamingExperienceSettings, plan.StreamingExperienceSettings),
		Tags:                        classifyChange(state.Tags, plan.Tags),
		TagsAll:                     classifyChange(state.TagsAll, plan.TagsAll),
		UserSettings:                classifyChange(state.UserSettings, plan.UserSettings),
	}
}

func classifyChange(state attr.Value, plan attr.Value) changeKind {
	if plan.IsUnknown() {
		return changeNone
	}
	if state.Equal(plan) {
		return changeNone
	}
	if plan.IsNull() {
		return changeCleared
	}
	return changeUpdated
}

func (d resourceDiff) HasRemoteChanges() bool {
	return d.Name.IsChanged() || d.Description.IsChanged() || d.DisplayName.IsChanged() || d.StorageConnectors.IsChanged() || d.RedirectUrl.IsChanged() || d.FeedbackUrl.IsChanged() || d.UserSettings.IsChanged() || d.ApplicationSettings.IsChanged() || d.AccessEndpoints.IsChanged() || d.EmbedHostDomains.IsChanged() || d.StreamingExperienceSettings.IsChanged()
}

func (d resourceDiff) RequiresTagApply() bool {
	return d.Tags.IsChanged() || d.TagsAll.IsChanged()
}
