// Code generated by schema-to-artifacts. DO NOT EDIT.

package stack

import types "github.com/hashicorp/terraform-plugin-framework/types"

type resourceModel struct {
	// A synthetic identifier for the stack, equal to the stack name. This value is managed by the provider and
	// cannot be set manually.
	ID types.String `tfsdk:"id"`
	// The name of the AppStream stack. Changing this value forces the stack to be replaced.
	Name types.String `tfsdk:"name"`
	// The stack description, if set. Must be 256 characters or fewer.
	Description types.String `tfsdk:"description"`
	// The name displayed to users in the AppStream user interface.
	DisplayName types.String `tfsdk:"display_name"`
	// Storage connectors that enable persistent storage for users of the stack.
	StorageConnectors types.Set `tfsdk:"storage_connectors"`
	// The URL users are redirected to after their AppStream streaming session ends.
	RedirectURL types.String `tfsdk:"redirect_url"`
	// The URL users are redirected to after clicking the **Send Feedback** link.
	FeedbackURL types.String `tfsdk:"feedback_url"`
	// Actions that are enabled or disabled for users during streaming sessions.
	UserSettings types.Set `tfsdk:"user_settings"`
	// Controls persistence of application settings for users of the stack.
	ApplicationSettings types.Object `tfsdk:"application_settings"`
	// Interface VPC endpoints through which users can connect to the stack.
	AccessEndpoints types.Set `tfsdk:"access_endpoints"`
	// Domains where streaming sessions can be embedded in an iframe.
	EmbedHostDomains types.Set `tfsdk:"embed_host_domains"`
	// Controls the preferred streaming protocol for the stack.
	StreamingExperienceSettings types.Object `tfsdk:"streaming_experience_settings"`
	// A map of tags assigned to the stack.
	Tags types.Map `tfsdk:"tags"`
	// A map of tags, including default tags, assigned to the stack.
	TagsAll types.Map `tfsdk:"tags_all"`
	// The Amazon Resource Name (ARN) of the AppStream stack.
	ARN types.String `tfsdk:"arn"`
	// The timestamp when the stack was created, in RFC 3339 format.
	CreatedTime types.String `tfsdk:"created_time"`
	// Informational list of errors reported by AWS for the stack. These errors do not affect Terraform lifecycle
	// behavior.
	StackErrors types.Set `tfsdk:"stack_errors"`
}
type resourceModelStorageConnectors struct {
	// The type of storage connector to enable for the stack.
	ConnectorType types.String `tfsdk:"connector_type"`
	// The resource identifier associated with the storage connector.
	ResourceIdentifier types.String `tfsdk:"resource_identifier"`
	// The domain names associated with the storage connector.
	Domains types.Set `tfsdk:"domains"`
	// The domain names that require administrator consent before access is granted.
	DomainsRequireAdminConsent types.Set `tfsdk:"domains_require_admin_consent"`
}
type resourceModelUserSettings struct {
	// The user action that can be enabled or disabled during a streaming session.
	Action types.String `tfsdk:"action"`
	// Specifies whether the action is enabled or disabled.
	Permission types.String `tfsdk:"permission"`
	// Specifies the maximum number of characters that can be copied for clipboard actions. This setting applies only
	// to `CLIPBOARD_COPY_FROM_LOCAL_DEVICE` and `CLIPBOARD_COPY_TO_LOCAL_DEVICE`. It cannot be set when permission
	// is `DISABLED`.
	MaximumLength types.Int32 `tfsdk:"maximum_length"`
}
type resourceModelApplicationSettings struct {
	// Whether application settings persistence is enabled.
	Enabled types.Bool `tfsdk:"enabled"`
	// The name of the application settings group.
	SettingsGroup types.String `tfsdk:"settings_group"`
	// The S3 bucket name where users persistent application settings are stored.
	S3BucketName types.String `tfsdk:"s3_bucket_name"`
}
type resourceModelAccessEndpoints struct {
	// The type of interface endpoint.
	EndpointType types.String `tfsdk:"endpoint_type"`
	// The identifier of the interface VPC endpoint.
	VpceID types.String `tfsdk:"vpce_id"`
}
type resourceModelStreamingExperienceSettings struct {
	// The preferred streaming protocol for the stack.
	PreferredProtocol types.String `tfsdk:"preferred_protocol"`
}
type resourceModelStackErrors struct {
	// The error code reported by AWS for the stack.
	ErrorCode types.String `tfsdk:"error_code"`
	// The human-readable error message reported by AWS.
	ErrorMessage types.String `tfsdk:"error_message"`
}
