// Code generated by schema-to-artifacts. DO NOT EDIT.

package imported_image

import attr "github.com/hashicorp/terraform-plugin-framework/attr"

// changeKind describes how a field transitions from state to plan.
type changeKind uint8

const (
	// changeNone means no actionable change for the field.
	changeNone changeKind = iota
	// changeUpdated means the field is set in plan and differs from state.
	changeUpdated
	// changeCleared means the field is explicitly set to null in plan.
	changeCleared
)

func (k changeKind) IsChanged() bool {
	return k != changeNone
}

func (k changeKind) IsUpdated() bool {
	return k == changeUpdated
}

func (k changeKind) IsCleared() bool {
	return k == changeCleared
}

type resourceDiff struct {
	ID                          changeKind
	Name                        changeKind
	IAMRoleARN                  changeKind
	SourceAmiID                 changeKind
	AgentSoftwareVersion        changeKind
	DisplayName                 changeKind
	Description                 changeKind
	RuntimeValidationConfig     changeKind
	AppCatalogConfig            changeKind
	Tags                        changeKind
	TagsAll                     changeKind
	ARN                         changeKind
	State                       changeKind
	StateChangeReason           changeKind
	CreatedTime                 changeKind
	Platform                    changeKind
	Visibility                  changeKind
	BaseImageARN                changeKind
	ImageBuilderSupported       changeKind
	ImageBuilderName            changeKind
	Applications                changeKind
	AppstreamAgentVersion       changeKind
	PublicBaseImageReleasedDate changeKind
	ImagePermissions            changeKind
	ImageErrors                 changeKind
	LatestAppstreamAgentVersion changeKind
	SupportedInstanceFamilies   changeKind
	DynamicAppProvidersEnabled  changeKind
	ImageSharedWithOthers       changeKind
	ManagedSoftwareIncluded     changeKind
	ImageType                   changeKind
}

func newResourceDiff(state resourceModel, plan resourceModel) resourceDiff {
	return resourceDiff{
		ARN:                         classifyChange(state.ARN, plan.ARN),
		AgentSoftwareVersion:        classifyChange(state.AgentSoftwareVersion, plan.AgentSoftwareVersion),
		AppCatalogConfig:            classifyChange(state.AppCatalogConfig, plan.AppCatalogConfig),
		Applications:                classifyChange(state.Applications, plan.Applications),
		AppstreamAgentVersion:       classifyChange(state.AppstreamAgentVersion, plan.AppstreamAgentVersion),
		BaseImageARN:                classifyChange(state.BaseImageARN, plan.BaseImageARN),
		CreatedTime:                 classifyChange(state.CreatedTime, plan.CreatedTime),
		Description:                 classifyChange(state.Description, plan.Description),
		DisplayName:                 classifyChange(state.DisplayName, plan.DisplayName),
		DynamicAppProvidersEnabled:  classifyChange(state.DynamicAppProvidersEnabled, plan.DynamicAppProvidersEnabled),
		IAMRoleARN:                  classifyChange(state.IAMRoleARN, plan.IAMRoleARN),
		ID:                          classifyChange(state.ID, plan.ID),
		ImageBuilderName:            classifyChange(state.ImageBuilderName, plan.ImageBuilderName),
		ImageBuilderSupported:       classifyChange(state.ImageBuilderSupported, plan.ImageBuilderSupported),
		ImageErrors:                 classifyChange(state.ImageErrors, plan.ImageErrors),
		ImagePermissions:            classifyChange(state.ImagePermissions, plan.ImagePermissions),
		ImageSharedWithOthers:       classifyChange(state.ImageSharedWithOthers, plan.ImageSharedWithOthers),
		ImageType:                   classifyChange(state.ImageType, plan.ImageType),
		LatestAppstreamAgentVersion: classifyChange(state.LatestAppstreamAgentVersion, plan.LatestAppstreamAgentVersion),
		ManagedSoftwareIncluded:     classifyChange(state.ManagedSoftwareIncluded, plan.ManagedSoftwareIncluded),
		Name:                        classifyChange(state.Name, plan.Name),
		Platform:                    classifyChange(state.Platform, plan.Platform),
		PublicBaseImageReleasedDate: classifyChange(state.PublicBaseImageReleasedDate, plan.PublicBaseImageReleasedDate),
		RuntimeValidationConfig:     classifyChange(state.RuntimeValidationConfig, plan.RuntimeValidationConfig),
		SourceAmiID:                 classifyChange(state.SourceAmiID, plan.SourceAmiID),
		State:                       classifyChange(state.State, plan.State),
		StateChangeReason:           classifyChange(state.StateChangeReason, plan.StateChangeReason),
		SupportedInstanceFamilies:   classifyChange(state.SupportedInstanceFamilies, plan.SupportedInstanceFamilies),
		Tags:                        classifyChange(state.Tags, plan.Tags),
		TagsAll:                     classifyChange(state.TagsAll, plan.TagsAll),
		Visibility:                  classifyChange(state.Visibility, plan.Visibility),
	}
}

func classifyChange(state attr.Value, plan attr.Value) changeKind {
	if plan.IsUnknown() {
		return changeNone
	}
	if state.Equal(plan) {
		return changeNone
	}
	if plan.IsNull() {
		return changeCleared
	}
	return changeUpdated
}

func (d resourceDiff) HasRemoteChanges() bool {
	return d.Name.IsChanged() || d.IAMRoleARN.IsChanged() || d.SourceAmiID.IsChanged() || d.AgentSoftwareVersion.IsChanged() || d.DisplayName.IsChanged() || d.Description.IsChanged() || d.RuntimeValidationConfig.IsChanged() || d.AppCatalogConfig.IsChanged()
}

func (d resourceDiff) RequiresTagApply() bool {
	return d.Tags.IsChanged() || d.TagsAll.IsChanged()
}
