// Code generated by schema-to-artifacts. DO NOT EDIT.

package fleet

import types "github.com/hashicorp/terraform-plugin-framework/types"

type dataSourceModel struct {
	// A synthetic identifier for the fleet, equal to the fleet name.
	ID types.String `tfsdk:"id"`
	// The name of the AppStream fleet to read.
	Name types.String `tfsdk:"name"`
	// The name of the AppStream image used to create the fleet, if set.
	ImageName types.String `tfsdk:"image_name"`
	// The ARN of the AppStream image used to create the fleet, if set.
	ImageARN types.String `tfsdk:"image_arn"`
	// The EC2 instance type used by the fleet.
	InstanceType types.String `tfsdk:"instance_type"`
	// The fleet type. Valid values are `ON_DEMAND`, `ALWAYS_ON`, or `ELASTIC`.
	FleetType types.String `tfsdk:"fleet_type"`
	// Describes the compute capacity configuration of the fleet, if applicable. For non-elastic fleets, either
	// instance-based or session-based capacity is returned.
	ComputeCapacity types.Object `tfsdk:"compute_capacity"`
	// The VPC configuration used by the fleet, if applicable. This configuration is present for elastic fleets.
	VPCConfig types.Object `tfsdk:"vpc_config"`
	// The maximum length of time that a streaming session can remain active.
	MaxUserDurationInSeconds types.Int32 `tfsdk:"max_user_duration_in_seconds"`
	// The amount of time that a disconnected session is allowed to remain active.
	DisconnectTimeoutInSeconds types.Int32 `tfsdk:"disconnect_timeout_in_seconds"`
	// The amount of time, in seconds, that a session can remain idle before being disconnected.
	IdleDisconnectTimeoutInSeconds types.Int32 `tfsdk:"idle_disconnect_timeout_in_seconds"`
	// The fleet description, if set.
	Description types.String `tfsdk:"description"`
	// The name displayed to users in the AppStream user interface.
	DisplayName types.String `tfsdk:"display_name"`
	// Whether Instance Metadata Service Version 1 (IMDSv1) is disabled for the AppStream fleet. If `true`, only
	// IMDSv2 is enabled. If `false`, both IMDSv1 and IMDSv2 are enabled.
	DisableIMDSV1 types.Bool `tfsdk:"disable_imds_v1"`
	// Whether instances in the fleet have access to the internet.
	EnableDefaultInternetAccess types.Bool `tfsdk:"enable_default_internet_access"`
	// The Active Directory configuration used by the fleet, if applicable.
	DomainJoinInfo types.Object `tfsdk:"domain_join_info"`
	// The ARN of the IAM role applied to fleet instances.
	IAMRoleARN types.String `tfsdk:"iam_role_arn"`
	// Controls which streaming protocol views are enabled.
	StreamView types.String `tfsdk:"stream_view"`
	// The platform of the fleet.
	Platform types.String `tfsdk:"platform"`
	// The maximum number of concurrent streaming sessions for an elastic fleet.
	MaxConcurrentSessions types.Int32 `tfsdk:"max_concurrent_sessions"`
	// The maximum number of user sessions allowed per fleet instance.
	MaxSessionsPerInstance types.Int32 `tfsdk:"max_sessions_per_instance"`
	// USB device filter rules configured for the fleet.
	USBDeviceFilterStrings types.Set `tfsdk:"usb_device_filter_strings"`
	// The S3 location of the session scripts configuration ZIP file, if set.
	SessionScriptS3Location types.Object `tfsdk:"session_script_s3_location"`
	// The root volume configuration of the fleet, if set.
	RootVolumeConfig types.Object `tfsdk:"root_volume_config"`
	// Tags assigned to the fleet.
	Tags types.Map `tfsdk:"tags"`
	// The Amazon Resource Name (ARN) of the AppStream fleet.
	ARN types.String `tfsdk:"arn"`
	// The timestamp when the fleet was created, in RFC 3339 format.
	CreatedTime types.String `tfsdk:"created_time"`
	// The state of the AppStream fleet.
	State types.String `tfsdk:"state"`
	// Informational list of errors reported by AWS for the fleet.
	FleetErrors types.Set `tfsdk:"fleet_errors"`
}
type dataSourceModelComputeCapacity struct {
	// The desired number of streaming instances for a single-session fleet.
	DesiredInstances types.Int32 `tfsdk:"desired_instances"`
	// The desired number of concurrent streaming sessions for a multi-session fleet.
	DesiredSessions types.Int32 `tfsdk:"desired_sessions"`
}
type dataSourceModelVPCConfig struct {
	// The subnet IDs associated with the fleet.
	SubnetIDs types.Set `tfsdk:"subnet_ids"`
	// The security group IDs associated with the fleet.
	SecurityGroupIDs types.Set `tfsdk:"security_group_ids"`
}
type dataSourceModelDomainJoinInfo struct {
	// The fully qualified domain name of the Active Directory.
	DirectoryName types.String `tfsdk:"directory_name"`
	// The distinguished name of the organizational unit for computer accounts.
	OrganizationalUnitDistinguishedName types.String `tfsdk:"organizational_unit_distinguished_name"`
}
type dataSourceModelSessionScriptS3Location struct {
	// The name of the S3 bucket.
	S3Bucket types.String `tfsdk:"s3_bucket"`
	// The S3 object key of the session script.
	S3Key types.String `tfsdk:"s3_key"`
}
type dataSourceModelRootVolumeConfig struct {
	// The size of the root volume, in GiB.
	VolumeSizeInGB types.Int32 `tfsdk:"volume_size_in_gb"`
}
type dataSourceModelFleetErrors struct {
	// The error code reported by AWS for the fleet.
	ErrorCode types.String `tfsdk:"error_code"`
	// The human-readable error message reported by AWS.
	ErrorMessage types.String `tfsdk:"error_message"`
}
