// Code generated by schema-to-artifacts. DO NOT EDIT.

package fleet

import types "github.com/hashicorp/terraform-plugin-framework/types"

type resourceModel struct {
	// A synthetic identifier for the fleet, equal to the fleet name. This value is managed by the provider and
	// cannot be set manually.
	ID types.String `tfsdk:"id"`
	// The name of the AppStream fleet. Changing this value forces the fleet to be replaced.
	Name types.String `tfsdk:"name"`
	// The name of the AppStream image used to create the fleet. This attribute is supported only for non-elastic
	// fleets. Either `image_name` or `image_arn` must be specified.
	ImageName types.String `tfsdk:"image_name"`
	// The ARN of the AppStream image used to create the fleet. This attribute is supported only for non-elastic
	// fleets. Either `image_name` or `image_arn` must be specified.
	ImageARN types.String `tfsdk:"image_arn"`
	// The EC2 instance type used by the fleet. This field is required for non-elastic fleets.
	InstanceType types.String `tfsdk:"instance_type"`
	// The fleet type. Valid values are `ON_DEMAND`, `ALWAYS_ON`, or `ELASTIC`.
	FleetType types.String `tfsdk:"fleet_type"`
	// Specifies the desired capacity for the fleet. Exactly one of `desired_instances` or `desired_sessions` must be
	// specified for non-elastic fleets. These attributes are mutually exclusive.
	ComputeCapacity types.Object `tfsdk:"compute_capacity"`
	// The VPC configuration used by the fleet. This block is required for elastic fleets.
	VPCConfig types.Object `tfsdk:"vpc_config"`
	// The maximum length of time that a streaming session can remain active.
	MaxUserDurationInSeconds types.Int32 `tfsdk:"max_user_duration_in_seconds"`
	// The amount of time that a disconnected session is allowed to remain active.
	DisconnectTimeoutInSeconds types.Int32 `tfsdk:"disconnect_timeout_in_seconds"`
	// The amount of time, in seconds, that a session can remain idle before being disconnected. Specify `0` to
	// disable idle disconnection. Otherwise, the value must be a multiple of 60 seconds between 60 and 36000 to
	// avoid AWS rounding behavior.
	IdleDisconnectTimeoutInSeconds types.Int32 `tfsdk:"idle_disconnect_timeout_in_seconds"`
	// The fleet description, if set.
	Description types.String `tfsdk:"description"`
	// The name displayed to users in the AppStream user interface.
	DisplayName types.String `tfsdk:"display_name"`
	// Whether Instance Metadata Service Version 1 (IMDSv1) is disabled for the AppStream fleet. If `true`, only
	// IMDSv2 is enabled. If `false`, both IMDSv1 and IMDSv2 are enabled. The default value is `false`.
	DisableIMDSV1 types.Bool `tfsdk:"disable_imds_v1"`
	// Whether instances in the fleet have access to the internet. The default value is `false`.
	EnableDefaultInternetAccess types.Bool `tfsdk:"enable_default_internet_access"`
	// Specifies the Active Directory domain and organizational unit used to join fleet instances to a Microsoft
	// Active Directory domain. This configuration is not supported for elastic fleets.
	DomainJoinInfo types.Object `tfsdk:"domain_join_info"`
	// The ARN of the IAM role applied to fleet instances.
	IAMRoleARN types.String `tfsdk:"iam_role_arn"`
	// Controls which streaming protocol views are enabled. The default value is `APP`
	StreamView types.String `tfsdk:"stream_view"`
	// The platform of the fleet. This attribute is only supported for elastic fleets and must be specified when
	// `fleet_type` is `ELASTIC`.
	Platform types.String `tfsdk:"platform"`
	// The maximum number of concurrent streaming sessions for an elastic fleet. This setting is required for elastic
	// fleets and is not allowed for other fleet types.
	MaxConcurrentSessions types.Int32 `tfsdk:"max_concurrent_sessions"`
	// The maximum number of user sessions allowed per fleet instance. This setting applies only to multi-session
	// fleets.
	MaxSessionsPerInstance types.Int32 `tfsdk:"max_sessions_per_instance"`
	// Defines which USB devices can be redirected to streaming sessions when using the Windows native client. This
	// setting is supported only for Windows fleets. For non-Windows platforms or non-native clients, this
	// configuration is accepted by AWS but ignored at runtime.
	USBDeviceFilterStrings types.Set `tfsdk:"usb_device_filter_strings"`
	// Specifies the S3 location of the session scripts configuration ZIP file. This setting applies only to elastic
	// fleets.
	SessionScriptS3Location types.Object `tfsdk:"session_script_s3_location"`
	// Specifies the root volume configuration for fleet instances.
	RootVolumeConfig types.Object `tfsdk:"root_volume_config"`
	// A map of tags assigned to the fleet.
	Tags types.Map `tfsdk:"tags"`
	// A map of tags, including default tags, assigned to the fleet.
	TagsAll types.Map `tfsdk:"tags_all"`
	// The runtime fleet state to enforce after create and update operations. Valid values are `INHERIT`, `RUNNING`,
	// and `STOPPED`. The default value is `INHERIT`, which preserves the fleet's existing runtime state.
	DesiredState types.String `tfsdk:"desired_state"`
	// Controls how updates are handled when AWS requires the fleet to be stopped. Valid values are `AUTO_STOP_START`
	// and `FAIL_IF_RUNNING`. If omitted, `AUTO_STOP_START` behavior is used.
	UpdateBehavior types.String `tfsdk:"update_behavior"`
	// The Amazon Resource Name (ARN) of the AppStream fleet.
	ARN types.String `tfsdk:"arn"`
	// The timestamp when the fleet was created, in RFC 3339 format.
	CreatedTime types.String `tfsdk:"created_time"`
	// The state of the AppStream fleet.
	State types.String `tfsdk:"state"`
	// Informational list of errors reported by AWS for the fleet. These errors do not affect Terraform lifecycle
	// behavior.
	FleetErrors types.Set `tfsdk:"fleet_errors"`
}
type resourceModelComputeCapacity struct {
	// The desired number of streaming instances for a single-session fleet.
	DesiredInstances types.Int32 `tfsdk:"desired_instances"`
	// The desired number of concurrent streaming sessions for a multi-session fleet.
	DesiredSessions types.Int32 `tfsdk:"desired_sessions"`
}
type resourceModelVPCConfig struct {
	// The subnet IDs for the fleet. This attribute is required for elastic fleets. Elastic fleets require at least
	// two subnets in different Availability Zones. The Availability Zone requirement is enforced by AWS.
	SubnetIDs types.Set `tfsdk:"subnet_ids"`
	// The security group IDs associated with the fleet.
	SecurityGroupIDs types.Set `tfsdk:"security_group_ids"`
}
type resourceModelDomainJoinInfo struct {
	// The fully qualified domain name of the Active Directory.
	DirectoryName types.String `tfsdk:"directory_name"`
	// The distinguished name of the organizational unit for computer accounts.
	OrganizationalUnitDistinguishedName types.String `tfsdk:"organizational_unit_distinguished_name"`
}
type resourceModelSessionScriptS3Location struct {
	// The name of the S3 bucket.
	S3Bucket types.String `tfsdk:"s3_bucket"`
	// The S3 object key of the session script.
	S3Key types.String `tfsdk:"s3_key"`
}
type resourceModelRootVolumeConfig struct {
	// The size of the root volume, in GiB.
	VolumeSizeInGB types.Int32 `tfsdk:"volume_size_in_gb"`
}
type resourceModelFleetErrors struct {
	// The error code reported by AWS for the fleet.
	ErrorCode types.String `tfsdk:"error_code"`
	// The human-readable error message reported by AWS.
	ErrorMessage types.String `tfsdk:"error_message"`
}
