// Code generated by schema-to-artifacts. DO NOT EDIT.

package fleet

import attr "github.com/hashicorp/terraform-plugin-framework/attr"

// changeKind describes how a field transitions from state to plan.
type changeKind uint8

const (
	// changeNone means no actionable change for the field.
	changeNone changeKind = iota
	// changeUpdated means the field is set in plan and differs from state.
	changeUpdated
	// changeCleared means the field is explicitly set to null in plan.
	changeCleared
)

func (k changeKind) IsChanged() bool {
	return k != changeNone
}

func (k changeKind) IsUpdated() bool {
	return k == changeUpdated
}

func (k changeKind) IsCleared() bool {
	return k == changeCleared
}

type resourceDiff struct {
	ID                             changeKind
	Name                           changeKind
	ImageName                      changeKind
	ImageARN                       changeKind
	InstanceType                   changeKind
	FleetType                      changeKind
	ComputeCapacity                changeKind
	VPCConfig                      changeKind
	MaxUserDurationInSeconds       changeKind
	DisconnectTimeoutInSeconds     changeKind
	IdleDisconnectTimeoutInSeconds changeKind
	Description                    changeKind
	DisplayName                    changeKind
	DisableIMDSV1                  changeKind
	EnableDefaultInternetAccess    changeKind
	DomainJoinInfo                 changeKind
	IAMRoleARN                     changeKind
	StreamView                     changeKind
	Platform                       changeKind
	MaxConcurrentSessions          changeKind
	MaxSessionsPerInstance         changeKind
	USBDeviceFilterStrings         changeKind
	SessionScriptS3Location        changeKind
	RootVolumeConfig               changeKind
	Tags                           changeKind
	TagsAll                        changeKind
	DesiredState                   changeKind
	UpdateBehavior                 changeKind
	ARN                            changeKind
	CreatedTime                    changeKind
	State                          changeKind
	FleetErrors                    changeKind
}

func newResourceDiff(state resourceModel, plan resourceModel) resourceDiff {
	return resourceDiff{
		ARN:                            classifyChange(state.ARN, plan.ARN),
		ComputeCapacity:                classifyChange(state.ComputeCapacity, plan.ComputeCapacity),
		CreatedTime:                    classifyChange(state.CreatedTime, plan.CreatedTime),
		Description:                    classifyChange(state.Description, plan.Description),
		DesiredState:                   classifyChange(state.DesiredState, plan.DesiredState),
		DisableIMDSV1:                  classifyChange(state.DisableIMDSV1, plan.DisableIMDSV1),
		DisconnectTimeoutInSeconds:     classifyChange(state.DisconnectTimeoutInSeconds, plan.DisconnectTimeoutInSeconds),
		DisplayName:                    classifyChange(state.DisplayName, plan.DisplayName),
		DomainJoinInfo:                 classifyChange(state.DomainJoinInfo, plan.DomainJoinInfo),
		EnableDefaultInternetAccess:    classifyChange(state.EnableDefaultInternetAccess, plan.EnableDefaultInternetAccess),
		FleetErrors:                    classifyChange(state.FleetErrors, plan.FleetErrors),
		FleetType:                      classifyChange(state.FleetType, plan.FleetType),
		IAMRoleARN:                     classifyChange(state.IAMRoleARN, plan.IAMRoleARN),
		ID:                             classifyChange(state.ID, plan.ID),
		IdleDisconnectTimeoutInSeconds: classifyChange(state.IdleDisconnectTimeoutInSeconds, plan.IdleDisconnectTimeoutInSeconds),
		ImageARN:                       classifyChange(state.ImageARN, plan.ImageARN),
		ImageName:                      classifyChange(state.ImageName, plan.ImageName),
		InstanceType:                   classifyChange(state.InstanceType, plan.InstanceType),
		MaxConcurrentSessions:          classifyChange(state.MaxConcurrentSessions, plan.MaxConcurrentSessions),
		MaxSessionsPerInstance:         classifyChange(state.MaxSessionsPerInstance, plan.MaxSessionsPerInstance),
		MaxUserDurationInSeconds:       classifyChange(state.MaxUserDurationInSeconds, plan.MaxUserDurationInSeconds),
		Name:                           classifyChange(state.Name, plan.Name),
		Platform:                       classifyChange(state.Platform, plan.Platform),
		RootVolumeConfig:               classifyChange(state.RootVolumeConfig, plan.RootVolumeConfig),
		SessionScriptS3Location:        classifyChange(state.SessionScriptS3Location, plan.SessionScriptS3Location),
		State:                          classifyChange(state.State, plan.State),
		StreamView:                     classifyChange(state.StreamView, plan.StreamView),
		Tags:                           classifyChange(state.Tags, plan.Tags),
		TagsAll:                        classifyChange(state.TagsAll, plan.TagsAll),
		USBDeviceFilterStrings:         classifyChange(state.USBDeviceFilterStrings, plan.USBDeviceFilterStrings),
		UpdateBehavior:                 classifyChange(state.UpdateBehavior, plan.UpdateBehavior),
		VPCConfig:                      classifyChange(state.VPCConfig, plan.VPCConfig),
	}
}

func classifyChange(state attr.Value, plan attr.Value) changeKind {
	if plan.IsUnknown() {
		return changeNone
	}
	if state.Equal(plan) {
		return changeNone
	}
	if plan.IsNull() {
		return changeCleared
	}
	return changeUpdated
}

func (d resourceDiff) HasRemoteChanges() bool {
	return d.Name.IsChanged() || d.ImageName.IsChanged() || d.ImageARN.IsChanged() || d.InstanceType.IsChanged() || d.FleetType.IsChanged() || d.ComputeCapacity.IsChanged() || d.VPCConfig.IsChanged() || d.MaxUserDurationInSeconds.IsChanged() || d.DisconnectTimeoutInSeconds.IsChanged() || d.IdleDisconnectTimeoutInSeconds.IsChanged() || d.Description.IsChanged() || d.DisplayName.IsChanged() || d.DisableIMDSV1.IsChanged() || d.EnableDefaultInternetAccess.IsChanged() || d.DomainJoinInfo.IsChanged() || d.IAMRoleARN.IsChanged() || d.StreamView.IsChanged() || d.Platform.IsChanged() || d.MaxConcurrentSessions.IsChanged() || d.MaxSessionsPerInstance.IsChanged() || d.USBDeviceFilterStrings.IsChanged() || d.SessionScriptS3Location.IsChanged() || d.RootVolumeConfig.IsChanged()
}

func (d resourceDiff) RequiresTagApply() bool {
	return d.Tags.IsChanged() || d.TagsAll.IsChanged()
}
