// Code generated by schema-to-artifacts. DO NOT EDIT.

package image

import types "github.com/hashicorp/terraform-plugin-framework/types"

type dataSourceModel struct {
	// The Amazon Resource Name (ARN) of the AppStream image.
	ID types.String `tfsdk:"id"`
	// The Amazon Resource Name (ARN) of the AppStream image. Cannot be used together with `name` or `name_regex`.
	ARN types.String `tfsdk:"arn"`
	// The name of the AppStream image. Cannot be used together with `arn` or `name_regex`. If multiple images with
	// the same name exist, the data source will return an error.
	Name types.String `tfsdk:"name"`
	// A regular expression used to match AppStream image names. Uses Go regular expression syntax. Cannot be used
	// together with `arn` or `name`. If the expression matches multiple images, the data source will return an
	// error.
	NameRegex types.String `tfsdk:"name_regex"`
	// The image visibility. Valid values are `PUBLIC`, `PRIVATE`, or `SHARED`.
	Visibility types.String `tfsdk:"visibility"`
	// Whether the most recent AppStream image is returned when multiple images match the selection criteria. If set
	// to `false` and multiple images match, the data source will return an error.
	MostRecent types.Bool `tfsdk:"most_recent"`
	// The ARN of the image from which this image was created.
	BaseImageARN types.String `tfsdk:"base_image_arn"`
	// The name displayed to users for the image, if set.
	DisplayName types.String `tfsdk:"display_name"`
	// The current state of the image.
	State types.String `tfsdk:"state"`
	// Whether an image builder can be launched from this image.
	ImageBuilderSupported types.Bool `tfsdk:"image_builder_supported"`
	// The name of the image builder used to create the image, if applicable.
	ImageBuilderName types.String `tfsdk:"image_builder_name"`
	// The operating system platform of the image.
	Platform types.String `tfsdk:"platform"`
	// The image description, if set.
	Description types.String `tfsdk:"description"`
	// The reason for the most recent image state change, if applicable.
	StateChangeReason types.Object `tfsdk:"state_change_reason"`
	// Applications that are associated with the image.
	Applications types.Set `tfsdk:"applications"`
	// The timestamp when the image was created, in RFC 3339 format.
	CreatedTime types.String `tfsdk:"created_time"`
	// The release date of the public base image, in RFC 3339 format.
	PublicBaseImageReleasedDate types.String `tfsdk:"public_base_image_released_date"`
	// The AppStream agent version used by the image.
	AppstreamAgentVersion types.String `tfsdk:"appstream_agent_version"`
	// Permissions granted for the image.
	ImagePermissions types.Object `tfsdk:"image_permissions"`
	// Errors reported by AWS during image creation or management.
	ImageErrors types.Set `tfsdk:"image_errors"`
	// Indicates whether the image uses the latest AppStream agent version.
	LatestAppstreamAgentVersion types.String `tfsdk:"latest_appstream_agent_version"`
	// The instance families supported by the image.
	SupportedInstanceFamilies types.Set `tfsdk:"supported_instance_families"`
	// Indicates whether dynamic app providers are enabled.
	DynamicAppProvidersEnabled types.String `tfsdk:"dynamic_app_providers_enabled"`
	// Indicates whether the image is shared with other AWS accounts.
	ImageSharedWithOthers types.String `tfsdk:"image_shared_with_others"`
	// Whether the image includes managed software.
	ManagedSoftwareIncluded types.Bool `tfsdk:"managed_software_included"`
	// The type of the image.
	ImageType types.String `tfsdk:"image_type"`
	// Tags assigned to the image.
	Tags types.Map `tfsdk:"tags"`
}
type dataSourceModelStateChangeReason struct {
	// The code describing why the image state changed.
	Code types.String `tfsdk:"code"`
	// The human-readable message describing the state change.
	Message types.String `tfsdk:"message"`
}
type dataSourceModelApplicationsIconS3Location struct {
	// The name of the S3 bucket.
	S3Bucket types.String `tfsdk:"s3_bucket"`
	// The S3 object key of the icon.
	S3Key types.String `tfsdk:"s3_key"`
}
type dataSourceModelApplications struct {
	// The name of the application.
	Name types.String `tfsdk:"name"`
	// The display name of the application.
	DisplayName types.String `tfsdk:"display_name"`
	// The URL of the application icon, if set.
	IconURL types.String `tfsdk:"icon_url"`
	// The path to the application executable.
	LaunchPath types.String `tfsdk:"launch_path"`
	// The parameters passed to the application at launch.
	LaunchParameters types.String `tfsdk:"launch_parameters"`
	// Whether the application is enabled.
	Enabled types.Bool `tfsdk:"enabled"`
	// Additional metadata associated with the application.
	Metadata types.Map `tfsdk:"metadata"`
	// The working directory of the application.
	WorkingDirectory types.String `tfsdk:"working_directory"`
	// The application description, if set.
	Description types.String `tfsdk:"description"`
	// The ARN of the application.
	ARN types.String `tfsdk:"arn"`
	// The ARN of the app block associated with the application.
	AppBlockARN types.String `tfsdk:"app_block_arn"`
	// The S3 location of the application icon, if set.
	IconS3Location types.Object `tfsdk:"icon_s3_location"`
	// The platforms on which the application can run.
	Platforms types.Set `tfsdk:"platforms"`
	// The instance families supported by the application.
	InstanceFamilies types.Set `tfsdk:"instance_families"`
	// The timestamp when the application was created, in RFC 3339 format.
	CreatedTime types.String `tfsdk:"created_time"`
}
type dataSourceModelImagePermissions struct {
	// Whether the image can be used by fleets.
	AllowFleet types.Bool `tfsdk:"allow_fleet"`
	// Whether the image can be used by image builders.
	AllowImageBuilder types.Bool `tfsdk:"allow_image_builder"`
}
type dataSourceModelImageErrors struct {
	// The error code reported by AWS.
	ErrorCode types.String `tfsdk:"error_code"`
	// The human-readable error message.
	ErrorMessage types.String `tfsdk:"error_message"`
	// The time the error occurred, in RFC 3339 format.
	ErrorTimestamp types.String `tfsdk:"error_timestamp"`
}
