// Code generated by schema-to-artifacts. DO NOT EDIT.

package application

import types "github.com/hashicorp/terraform-plugin-framework/types"

type dataSourceModel struct {
	// The Amazon Resource Name (ARN) of the AppStream application.
	ID types.String `tfsdk:"id"`
	// The Amazon Resource Name (ARN) of the AppStream application.
	ARN types.String `tfsdk:"arn"`
	// The name of the AppStream application.
	Name types.String `tfsdk:"name"`
	// The name displayed to users in the AppStream application catalog, if set.
	DisplayName types.String `tfsdk:"display_name"`
	// The application description, if set.
	Description types.String `tfsdk:"description"`
	// Specifies the S3 location of the application icon, if set.
	IconS3Location types.Object `tfsdk:"icon_s3_location"`
	// The path to the application executable within the image.
	LaunchPath types.String `tfsdk:"launch_path"`
	// The working directory of the application, if set.
	WorkingDirectory types.String `tfsdk:"working_directory"`
	// The parameters passed to the application at launch, if set.
	LaunchParameters types.String `tfsdk:"launch_parameters"`
	// The platforms on which the application can run.
	Platforms types.Set `tfsdk:"platforms"`
	// The instance families supported by the application.
	InstanceFamilies types.Set `tfsdk:"instance_families"`
	// The ARN of the app block associated with the application.
	AppBlockARN types.String `tfsdk:"app_block_arn"`
	// Tags assigned to the application.
	Tags types.Map `tfsdk:"tags"`
	// The timestamp when the application was created, in RFC 3339 format.
	CreatedTime types.String `tfsdk:"created_time"`
}
type dataSourceModelIconS3Location struct {
	// The name of the S3 bucket containing the application icon.
	S3Bucket types.String `tfsdk:"s3_bucket"`
	// The S3 object key of the application icon.
	S3Key types.String `tfsdk:"s3_key"`
}
