// Code generated by schema-to-artifacts. DO NOT EDIT.

package application

import attr "github.com/hashicorp/terraform-plugin-framework/attr"

// changeKind describes how a field transitions from state to plan.
type changeKind uint8

const (
	// changeNone means no actionable change for the field.
	changeNone changeKind = iota
	// changeUpdated means the field is set in plan and differs from state.
	changeUpdated
	// changeCleared means the field is explicitly set to null in plan.
	changeCleared
)

func (k changeKind) IsChanged() bool {
	return k != changeNone
}

func (k changeKind) IsUpdated() bool {
	return k == changeUpdated
}

func (k changeKind) IsCleared() bool {
	return k == changeCleared
}

type resourceDiff struct {
	ID               changeKind
	Name             changeKind
	DisplayName      changeKind
	Description      changeKind
	IconS3Location   changeKind
	LaunchPath       changeKind
	WorkingDirectory changeKind
	LaunchParameters changeKind
	Platforms        changeKind
	InstanceFamilies changeKind
	AppBlockARN      changeKind
	Tags             changeKind
	TagsAll          changeKind
	ARN              changeKind
	CreatedTime      changeKind
}

func newResourceDiff(state resourceModel, plan resourceModel) resourceDiff {
	return resourceDiff{
		ARN:              classifyChange(state.ARN, plan.ARN),
		AppBlockARN:      classifyChange(state.AppBlockARN, plan.AppBlockARN),
		CreatedTime:      classifyChange(state.CreatedTime, plan.CreatedTime),
		Description:      classifyChange(state.Description, plan.Description),
		DisplayName:      classifyChange(state.DisplayName, plan.DisplayName),
		ID:               classifyChange(state.ID, plan.ID),
		IconS3Location:   classifyChange(state.IconS3Location, plan.IconS3Location),
		InstanceFamilies: classifyChange(state.InstanceFamilies, plan.InstanceFamilies),
		LaunchParameters: classifyChange(state.LaunchParameters, plan.LaunchParameters),
		LaunchPath:       classifyChange(state.LaunchPath, plan.LaunchPath),
		Name:             classifyChange(state.Name, plan.Name),
		Platforms:        classifyChange(state.Platforms, plan.Platforms),
		Tags:             classifyChange(state.Tags, plan.Tags),
		TagsAll:          classifyChange(state.TagsAll, plan.TagsAll),
		WorkingDirectory: classifyChange(state.WorkingDirectory, plan.WorkingDirectory),
	}
}

func classifyChange(state attr.Value, plan attr.Value) changeKind {
	if plan.IsUnknown() {
		return changeNone
	}
	if state.Equal(plan) {
		return changeNone
	}
	if plan.IsNull() {
		return changeCleared
	}
	return changeUpdated
}

func (d resourceDiff) HasRemoteChanges() bool {
	return d.Name.IsChanged() || d.DisplayName.IsChanged() || d.Description.IsChanged() || d.IconS3Location.IsChanged() || d.LaunchPath.IsChanged() || d.WorkingDirectory.IsChanged() || d.LaunchParameters.IsChanged() || d.Platforms.IsChanged() || d.InstanceFamilies.IsChanged() || d.AppBlockARN.IsChanged()
}

func (d resourceDiff) RequiresTagApply() bool {
	return d.Tags.IsChanged() || d.TagsAll.IsChanged()
}
