// Code generated by schema-to-artifacts. DO NOT EDIT.

package copied_image

import types "github.com/hashicorp/terraform-plugin-framework/types"

type resourceModel struct {
	// A synthetic identifier for the copied image, composed of the name and destination region. This value is
	// managed by the provider and cannot be set manually.
	ID types.String `tfsdk:"id"`
	// A unique destination name for the copied image. Changing this value forces the copied image to be replaced.
	Name types.String `tfsdk:"name"`
	// A description for the copied image. Changing this value forces the copied image to be replaced.
	Description types.String `tfsdk:"description"`
	// The AWS region where the copied image is created. Changing this value forces the copied image to be replaced.
	DestinationRegion types.String `tfsdk:"destination_region"`
	// The name of the source image used for the copy operation. Changing this value forces the copied image to be
	// replaced. After import, this create-time input must be set explicitly in configuration.
	SourceImageName types.String `tfsdk:"source_image_name"`
	// A map of tags assigned to the copied image.
	Tags types.Map `tfsdk:"tags"`
	// A map of tags, including default tags, assigned to the copied image.
	TagsAll types.Map `tfsdk:"tags_all"`
	// The Amazon Resource Name (ARN) of the AppStream copied image.
	ARN types.String `tfsdk:"arn"`
	// The current state of the AppStream copied image.
	State types.String `tfsdk:"state"`
	// The reason for the most recent AppStream copied image state change, if applicable.
	StateChangeReason types.Object `tfsdk:"state_change_reason"`
	// The timestamp when the AppStream copied image was created, in RFC 3339 format.
	CreatedTime types.String `tfsdk:"created_time"`
	// The operating system platform of the AppStream copied image.
	Platform types.String `tfsdk:"platform"`
	// The visibility of the AppStream copied image, such as `PRIVATE` or `SHARED`.
	Visibility types.String `tfsdk:"visibility"`
	// The ARN of the image from which this image was created.
	BaseImageARN types.String `tfsdk:"base_image_arn"`
	// Whether an AppStream image builder can be launched from this copied image.
	ImageBuilderSupported types.Bool `tfsdk:"image_builder_supported"`
	// The name of the image builder used to create the image, if applicable.
	ImageBuilderName types.String `tfsdk:"image_builder_name"`
	// Applications that are associated with the image.
	Applications types.Set `tfsdk:"applications"`
	// The AppStream agent version currently associated with the copied image.
	AppstreamAgentVersion types.String `tfsdk:"appstream_agent_version"`
	// The release date of the public base image, in RFC 3339 format, if available.
	PublicBaseImageReleasedDate types.String `tfsdk:"public_base_image_released_date"`
	// Permissions granted for the image.
	ImagePermissions types.Object `tfsdk:"image_permissions"`
	// Errors reported by AWS during image creation or management.
	ImageErrors types.Set `tfsdk:"image_errors"`
	// Indicates whether the image uses the latest AppStream agent version.
	LatestAppstreamAgentVersion types.String `tfsdk:"latest_appstream_agent_version"`
	// The instance families supported by the image.
	SupportedInstanceFamilies types.Set `tfsdk:"supported_instance_families"`
	// Indicates whether dynamic app providers are enabled.
	DynamicAppProvidersEnabled types.String `tfsdk:"dynamic_app_providers_enabled"`
	// Indicates whether the image is shared with other AWS accounts.
	ImageSharedWithOthers types.String `tfsdk:"image_shared_with_others"`
	// Whether the image includes managed software.
	ManagedSoftwareIncluded types.Bool `tfsdk:"managed_software_included"`
	// The type of the image.
	ImageType types.String `tfsdk:"image_type"`
}
type resourceModelStateChangeReason struct {
	// The code describing why the AppStream copied image state changed.
	Code types.String `tfsdk:"code"`
	// The human-readable message describing the AppStream copied image state change.
	Message types.String `tfsdk:"message"`
}
type resourceModelApplicationsIconS3Location struct {
	// The name of the S3 bucket.
	S3Bucket types.String `tfsdk:"s3_bucket"`
	// The S3 object key of the icon.
	S3Key types.String `tfsdk:"s3_key"`
}
type resourceModelApplications struct {
	// The name of the application.
	Name types.String `tfsdk:"name"`
	// The display name of the application.
	DisplayName types.String `tfsdk:"display_name"`
	// The URL of the application icon, if set.
	IconURL types.String `tfsdk:"icon_url"`
	// The path to the application executable.
	LaunchPath types.String `tfsdk:"launch_path"`
	// The parameters passed to the application at launch.
	LaunchParameters types.String `tfsdk:"launch_parameters"`
	// Whether the application is enabled.
	Enabled types.Bool `tfsdk:"enabled"`
	// Additional metadata associated with the application.
	Metadata types.Map `tfsdk:"metadata"`
	// The working directory of the application.
	WorkingDirectory types.String `tfsdk:"working_directory"`
	// The application description, if set.
	Description types.String `tfsdk:"description"`
	// The ARN of the application.
	ARN types.String `tfsdk:"arn"`
	// The ARN of the app block associated with the application.
	AppBlockARN types.String `tfsdk:"app_block_arn"`
	// The S3 location of the application icon, if set.
	IconS3Location types.Object `tfsdk:"icon_s3_location"`
	// The platforms on which the application can run.
	Platforms types.Set `tfsdk:"platforms"`
	// The instance families supported by the application.
	InstanceFamilies types.Set `tfsdk:"instance_families"`
	// The timestamp when the application was created, in RFC 3339 format.
	CreatedTime types.String `tfsdk:"created_time"`
}
type resourceModelImagePermissions struct {
	// Whether the image can be used by fleets.
	AllowFleet types.Bool `tfsdk:"allow_fleet"`
	// Whether the image can be used by image builders.
	AllowImageBuilder types.Bool `tfsdk:"allow_image_builder"`
}
type resourceModelImageErrors struct {
	// The error code reported by AWS.
	ErrorCode types.String `tfsdk:"error_code"`
	// The human-readable error message.
	ErrorMessage types.String `tfsdk:"error_message"`
	// The time the error occurred, in RFC 3339 format.
	ErrorTimestamp types.String `tfsdk:"error_timestamp"`
}
