// Code generated by schema-to-artifacts. DO NOT EDIT.

package stack_theme

import types "github.com/hashicorp/terraform-plugin-framework/types"

type dataSourceModel struct {
	// A synthetic identifier for the stack theme, equal to the stack name.
	ID types.String `tfsdk:"id"`
	// The name of the AppStream stack whose theme is read.
	StackName types.String `tfsdk:"stack_name"`
	// The title displayed at the top of the browser tab during streaming sessions.
	TitleText types.String `tfsdk:"title_text"`
	// The color theme applied to links, text, buttons, and accents in the catalog page.
	ThemeStyling types.String `tfsdk:"theme_styling"`
	// Links displayed in the footer of the streaming application catalog page.
	FooterLinks types.Set `tfsdk:"footer_links"`
	// The current state of the AppStream stack theme.
	State types.String `tfsdk:"state"`
	// The URL of the logo displayed in the catalog page header.
	ThemeOrganizationLogoUrl types.String `tfsdk:"theme_organization_logo_url"`
	// The URL of the icon displayed in the browser tab during streaming sessions.
	ThemeFaviconUrl types.String `tfsdk:"theme_favicon_url"`
	// The timestamp when the stack theme was created, in RFC 3339 format.
	CreatedTime types.String `tfsdk:"created_time"`
}
type dataSourceModelFooterLinks struct {
	// The name displayed for the footer link.
	DisplayName types.String `tfsdk:"display_name"`
	// The URL that the footer link points to.
	FooterLinkUrl types.String `tfsdk:"footer_link_url"`
}
