// Code generated by schema-to-artifacts. DO NOT EDIT.

package stack_theme

import types "github.com/hashicorp/terraform-plugin-framework/types"

type resourceModel struct {
	// A synthetic identifier for the stack theme, equal to the stack name. This value is managed by the provider and
	// cannot be set manually.
	ID types.String `tfsdk:"id"`
	// The name of the AppStream stack that the theme is applied to. Changing this value forces the theme to be
	// replaced.
	StackName types.String `tfsdk:"stack_name"`
	// The title displayed at the top of the browser tab during application streaming sessions.
	TitleText types.String `tfsdk:"title_text"`
	// The color theme applied to links, text, buttons, and accents in the streaming catalog page.
	ThemeStyling types.String `tfsdk:"theme_styling"`
	// Specifies the Amazon S3 location of the organization logo displayed in the header of the streaming application
	// catalog page.
	OrganizationLogoS3Location types.Object `tfsdk:"organization_logo_s3_location"`
	// Specifies the Amazon S3 location of the favicon displayed in browser tabs during application streaming
	// sessions.
	FaviconS3Location types.Object `tfsdk:"favicon_s3_location"`
	// Optional links displayed in the footer of the streaming application catalog page, such as support,
	// documentation, or marketing links.
	FooterLinks types.Set `tfsdk:"footer_links"`
	// The current state of the AppStream stack theme.
	State types.String `tfsdk:"state"`
	// The timestamp when the stack theme was created, in RFC 3339 format.
	CreatedTime types.String `tfsdk:"created_time"`
	// The URL of the logo that is displayed in the header of the streaming application catalog page.
	ThemeOrganizationLogoURL types.String `tfsdk:"theme_organization_logo_url"`
	// The URL of the icon that is displayed at the top of the browser tab during application streaming sessions.
	ThemeFaviconURL types.String `tfsdk:"theme_favicon_url"`
}
type resourceModelOrganizationLogoS3Location struct {
	// The name of the Amazon S3 bucket.
	S3Bucket types.String `tfsdk:"s3_bucket"`
	// The S3 object key of the organization logo.
	S3Key types.String `tfsdk:"s3_key"`
}
type resourceModelFaviconS3Location struct {
	// The name of the Amazon S3 bucket.
	S3Bucket types.String `tfsdk:"s3_bucket"`
	// The S3 object key of the favicon.
	S3Key types.String `tfsdk:"s3_key"`
}
type resourceModelFooterLinks struct {
	// The name displayed for the footer link in the catalog page.
	DisplayName types.String `tfsdk:"display_name"`
	// The URL that the footer link points to.
	FooterLinkURL types.String `tfsdk:"footer_link_url"`
}
