// Code generated by schema-to-artifacts. DO NOT EDIT.

package stack_theme

import attr "github.com/hashicorp/terraform-plugin-framework/attr"

// changeKind describes how a field transitions from state to plan.
type changeKind uint8

const (
	// changeNone means no actionable change for the field.
	changeNone changeKind = iota
	// changeUpdated means the field is set in plan and differs from state.
	changeUpdated
	// changeCleared means the field is explicitly set to null in plan.
	changeCleared
)

func (k changeKind) IsChanged() bool {
	return k != changeNone
}

func (k changeKind) IsUpdated() bool {
	return k == changeUpdated
}

func (k changeKind) IsCleared() bool {
	return k == changeCleared
}

type resourceDiff struct {
	ID                         changeKind
	StackName                  changeKind
	TitleText                  changeKind
	ThemeStyling               changeKind
	OrganizationLogoS3Location changeKind
	FaviconS3Location          changeKind
	FooterLinks                changeKind
	State                      changeKind
	CreatedTime                changeKind
	ThemeOrganizationLogoURL   changeKind
	ThemeFaviconURL            changeKind
}

func newResourceDiff(state resourceModel, plan resourceModel) resourceDiff {
	return resourceDiff{
		CreatedTime:                classifyChange(state.CreatedTime, plan.CreatedTime),
		FaviconS3Location:          classifyChange(state.FaviconS3Location, plan.FaviconS3Location),
		FooterLinks:                classifyChange(state.FooterLinks, plan.FooterLinks),
		ID:                         classifyChange(state.ID, plan.ID),
		OrganizationLogoS3Location: classifyChange(state.OrganizationLogoS3Location, plan.OrganizationLogoS3Location),
		StackName:                  classifyChange(state.StackName, plan.StackName),
		State:                      classifyChange(state.State, plan.State),
		ThemeFaviconURL:            classifyChange(state.ThemeFaviconURL, plan.ThemeFaviconURL),
		ThemeOrganizationLogoURL:   classifyChange(state.ThemeOrganizationLogoURL, plan.ThemeOrganizationLogoURL),
		ThemeStyling:               classifyChange(state.ThemeStyling, plan.ThemeStyling),
		TitleText:                  classifyChange(state.TitleText, plan.TitleText),
	}
}

func classifyChange(state attr.Value, plan attr.Value) changeKind {
	if plan.IsUnknown() {
		return changeNone
	}
	if state.Equal(plan) {
		return changeNone
	}
	if plan.IsNull() {
		return changeCleared
	}
	return changeUpdated
}

func (d resourceDiff) HasRemoteChanges() bool {
	return d.StackName.IsChanged() || d.TitleText.IsChanged() || d.ThemeStyling.IsChanged() || d.OrganizationLogoS3Location.IsChanged() || d.FaviconS3Location.IsChanged() || d.FooterLinks.IsChanged()
}

func (d resourceDiff) RequiresTagApply() bool {
	return false
}
