// Code generated by schema-to-artifacts. DO NOT EDIT.

package associate_application_fleet

import types "github.com/hashicorp/terraform-plugin-framework/types"

type resourceModel struct {
	// A synthetic identifier for the association, composed of the fleet name and application ARN. This value is
	// managed by the provider and cannot be set manually.
	ID types.String `tfsdk:"id"`
	// The name of the AppStream fleet to associate with the application. Changing this value forces the association
	// to be replaced.
	FleetName types.String `tfsdk:"fleet_name"`
	// The ARN of the AppStream application to associate with the fleet. Changing this value forces the association
	// to be replaced.
	ApplicationARN types.String `tfsdk:"application_arn"`
}
