// Code generated by schema-to-artifacts. DO NOT EDIT.

package app_block_builder

import types "github.com/hashicorp/terraform-plugin-framework/types"

type resourceModel struct {
	// A synthetic identifier for the app block builder, equal to the app block builder name. This value is managed
	// by the provider and cannot be set manually.
	ID types.String `tfsdk:"id"`
	// The name of the AppStream app block builder. Changing this value forces the app block builder to be replaced.
	Name types.String `tfsdk:"name"`
	// The instance type used when launching the app block builder.
	InstanceType types.String `tfsdk:"instance_type"`
	// The operating system platform of the app block builder.
	Platform types.String `tfsdk:"platform"`
	// The app block builder description, if set.
	Description types.String `tfsdk:"description"`
	// The display name of the app block builder shown in the AppStream user interface.
	DisplayName types.String `tfsdk:"display_name"`
	// Whether Instance Metadata Service Version 1 (IMDSv1) is disabled for the AppStream app block builder. If
	// `true`, only IMDSv2 is enabled. If `false`, both IMDSv1 and IMDSv2 are enabled. The default value is `false`.
	DisableIMDSV1 types.Bool `tfsdk:"disable_imds_v1"`
	// The VPC configuration used by the app block builder. App block builders require at least two subnet IDs in
	// different Availability Zones.
	VPCConfig types.Object `tfsdk:"vpc_config"`
	// The ARN of the IAM role applied to the app block builder.
	IAMRoleARN types.String `tfsdk:"iam_role_arn"`
	// Whether the app block builder has access to the internet. The default value is `false`.
	EnableDefaultInternetAccess types.Bool `tfsdk:"enable_default_internet_access"`
	// Interface VPC endpoints through which administrators can connect to the app block builder.
	AccessEndpoints types.Set `tfsdk:"access_endpoints"`
	// A map of tags assigned to the app block builder.
	Tags types.Map `tfsdk:"tags"`
	// A map of tags, including default tags, assigned to the app block builder.
	TagsAll types.Map `tfsdk:"tags_all"`
	// The Amazon Resource Name (ARN) of the AppStream app block builder.
	ARN types.String `tfsdk:"arn"`
	// The timestamp when the app block builder was created, in RFC 3339 format.
	CreatedTime types.String `tfsdk:"created_time"`
	// The state of the AppStream app block builder.
	State types.String `tfsdk:"state"`
	// The reason for the most recent app block builder state change, if applicable.
	StateChangeReason types.Object `tfsdk:"state_change_reason"`
	// Informational list of errors reported by AWS for the app block builder. These errors do not affect Terraform
	// lifecycle behavior.
	AppBlockBuilderErrors types.Set `tfsdk:"app_block_builder_errors"`
}
type resourceModelVPCConfig struct {
	// The subnet IDs in which the app block builder is launched. Specify at least two subnet IDs in different
	// availability zones.
	SubnetIDs types.Set `tfsdk:"subnet_ids"`
	// The security group IDs associated with the app block builder.
	SecurityGroupIDs types.Set `tfsdk:"security_group_ids"`
}
type resourceModelAccessEndpoints struct {
	// The type of interface endpoint.
	EndpointType types.String `tfsdk:"endpoint_type"`
	// The identifier of the interface VPC endpoint.
	VpceID types.String `tfsdk:"vpce_id"`
}
type resourceModelStateChangeReason struct {
	// The code describing why the app block builder state changed.
	Code types.String `tfsdk:"code"`
	// The human-readable message describing the state change.
	Message types.String `tfsdk:"message"`
}
type resourceModelAppBlockBuilderErrors struct {
	// The error code reported by AWS for the app block builder.
	ErrorCode types.String `tfsdk:"error_code"`
	// The human-readable error message reported by AWS.
	ErrorMessage types.String `tfsdk:"error_message"`
	// The timestamp when the error occurred, in RFC 3339 format.
	ErrorTimestamp types.String `tfsdk:"error_timestamp"`
}
