// Code generated by schema-to-artifacts. DO NOT EDIT.

package app_block_builder

import attr "github.com/hashicorp/terraform-plugin-framework/attr"

// changeKind describes how a field transitions from state to plan.
type changeKind uint8

const (
	// changeNone means no actionable change for the field.
	changeNone changeKind = iota
	// changeUpdated means the field is set in plan and differs from state.
	changeUpdated
	// changeCleared means the field is explicitly set to null in plan.
	changeCleared
)

func (k changeKind) IsChanged() bool {
	return k != changeNone
}

func (k changeKind) IsUpdated() bool {
	return k == changeUpdated
}

func (k changeKind) IsCleared() bool {
	return k == changeCleared
}

type resourceDiff struct {
	ID                          changeKind
	Name                        changeKind
	InstanceType                changeKind
	Platform                    changeKind
	Description                 changeKind
	DisplayName                 changeKind
	DisableIMDSV1               changeKind
	VPCConfig                   changeKind
	IAMRoleARN                  changeKind
	EnableDefaultInternetAccess changeKind
	AccessEndpoints             changeKind
	Tags                        changeKind
	TagsAll                     changeKind
	ARN                         changeKind
	CreatedTime                 changeKind
	State                       changeKind
	StateChangeReason           changeKind
	AppBlockBuilderErrors       changeKind
}

func newResourceDiff(state resourceModel, plan resourceModel) resourceDiff {
	return resourceDiff{
		ARN:                         classifyChange(state.ARN, plan.ARN),
		AccessEndpoints:             classifyChange(state.AccessEndpoints, plan.AccessEndpoints),
		AppBlockBuilderErrors:       classifyChange(state.AppBlockBuilderErrors, plan.AppBlockBuilderErrors),
		CreatedTime:                 classifyChange(state.CreatedTime, plan.CreatedTime),
		Description:                 classifyChange(state.Description, plan.Description),
		DisableIMDSV1:               classifyChange(state.DisableIMDSV1, plan.DisableIMDSV1),
		DisplayName:                 classifyChange(state.DisplayName, plan.DisplayName),
		EnableDefaultInternetAccess: classifyChange(state.EnableDefaultInternetAccess, plan.EnableDefaultInternetAccess),
		IAMRoleARN:                  classifyChange(state.IAMRoleARN, plan.IAMRoleARN),
		ID:                          classifyChange(state.ID, plan.ID),
		InstanceType:                classifyChange(state.InstanceType, plan.InstanceType),
		Name:                        classifyChange(state.Name, plan.Name),
		Platform:                    classifyChange(state.Platform, plan.Platform),
		State:                       classifyChange(state.State, plan.State),
		StateChangeReason:           classifyChange(state.StateChangeReason, plan.StateChangeReason),
		Tags:                        classifyChange(state.Tags, plan.Tags),
		TagsAll:                     classifyChange(state.TagsAll, plan.TagsAll),
		VPCConfig:                   classifyChange(state.VPCConfig, plan.VPCConfig),
	}
}

func classifyChange(state attr.Value, plan attr.Value) changeKind {
	if plan.IsUnknown() {
		return changeNone
	}
	if state.Equal(plan) {
		return changeNone
	}
	if plan.IsNull() {
		return changeCleared
	}
	return changeUpdated
}

func (d resourceDiff) HasRemoteChanges() bool {
	return d.Name.IsChanged() || d.InstanceType.IsChanged() || d.Platform.IsChanged() || d.Description.IsChanged() || d.DisplayName.IsChanged() || d.DisableIMDSV1.IsChanged() || d.VPCConfig.IsChanged() || d.IAMRoleARN.IsChanged() || d.EnableDefaultInternetAccess.IsChanged() || d.AccessEndpoints.IsChanged()
}

func (d resourceDiff) RequiresTagApply() bool {
	return d.Tags.IsChanged() || d.TagsAll.IsChanged()
}
