// Copyright St3ffn 2025, 2026
// SPDX-License-Identifier: MPL-2.0

package schematomodel

import (
	"bytes"
	"fmt"
	"strings"

	jen "github.com/dave/jennifer/jen"
)

func render(pkgName string, rootModel modelType, nestedModels []modelType) ([]byte, error) {
	f := jen.NewFile(pkgName)
	f.HeaderComment("Code generated by schema-to-artifacts. DO NOT EDIT.")

	renderModel(f, rootModel)
	for _, model := range nestedModels {
		renderModel(f, model)
	}

	var b bytes.Buffer
	if err := f.Render(&b); err != nil {
		return nil, fmt.Errorf("render model file: %w", err)
	}

	return b.Bytes(), nil
}

func renderModel(f *jen.File, model modelType) {
	f.Type().Id(model.Name).StructFunc(func(g *jen.Group) {
		for _, fld := range model.Fields {
			for _, line := range wrapComment(fld.Comment, 110) {
				g.Comment(line)
			}
			g.Id(fld.Name).Add(jenType(fld.Type)).Tag(map[string]string{"tfsdk": fld.Tag})
		}
	})
}

func jenType(typeName string) *jen.Statement {
	if strings.HasPrefix(typeName, "types.") {
		return jen.Qual(
			"github.com/hashicorp/terraform-plugin-framework/types",
			strings.TrimPrefix(typeName, "types."),
		)
	}

	return jen.Id(typeName)
}

func wrapComment(text string, width int) []string {
	t := strings.TrimSpace(text)
	if t == "" {
		return nil
	}

	parts := strings.Fields(strings.ReplaceAll(t, "\n", " "))
	if len(parts) == 0 {
		return nil
	}

	lines := make([]string, 0, 2)
	line := parts[0]
	for _, part := range parts[1:] {
		if len(line)+1+len(part) <= width {
			line += " " + part
			continue
		}
		lines = append(lines, line)
		line = part
	}
	lines = append(lines, line)
	return lines
}
