// Copyright St3ffn 2025, 2026
// SPDX-License-Identifier: MPL-2.0

package schematomodel

import (
	"bytes"
	"fmt"

	jen "github.com/dave/jennifer/jen"
)

func renderDiff(pkgName string, rootModel modelType, diffTypeName, constructorName string) ([]byte, error) {
	f := jen.NewFile(pkgName)
	f.HeaderComment("Code generated by schema-to-artifacts. DO NOT EDIT.")

	f.Comment("changeKind describes how a field transitions from state to plan.")
	f.Type().Id("changeKind").Uint8()
	f.Line()

	f.Const().Defs(
		jen.Comment("changeNone means no actionable change for the field."),
		jen.Id("changeNone").Id("changeKind").Op("=").Iota(),
		jen.Comment("changeUpdated means the field is set in plan and differs from state."),
		jen.Id("changeUpdated"),
		jen.Comment("changeCleared means the field is explicitly set to null in plan."),
		jen.Id("changeCleared"),
	)
	f.Line()

	f.Func().
		Params(jen.Id("k").Id("changeKind")).
		Id("IsChanged").
		Params().
		Bool().
		Block(
			jen.Return(jen.Id("k").Op("!=").Id("changeNone")),
		)
	f.Line()

	f.Func().
		Params(jen.Id("k").Id("changeKind")).
		Id("IsUpdated").
		Params().
		Bool().
		Block(
			jen.Return(jen.Id("k").Op("==").Id("changeUpdated")),
		)
	f.Line()

	f.Func().
		Params(jen.Id("k").Id("changeKind")).
		Id("IsCleared").
		Params().
		Bool().
		Block(
			jen.Return(jen.Id("k").Op("==").Id("changeCleared")),
		)
	f.Line()

	f.Type().Id(diffTypeName).StructFunc(func(g *jen.Group) {
		for _, fld := range rootModel.Fields {
			g.Id(fld.Name).Id("changeKind")
		}
	})
	f.Line()

	f.Func().
		Id(constructorName).
		Params(
			jen.Id("state").Id(rootModel.Name),
			jen.Id("plan").Id(rootModel.Name),
		).
		Id(diffTypeName).
		Block(
			jen.Return(
				jen.Id(diffTypeName).Values(jen.DictFunc(func(d jen.Dict) {
					for _, fld := range rootModel.Fields {
						d[jen.Id(fld.Name)] = jen.Id("classifyChange").Call(
							jen.Id("state").Dot(fld.Name),
							jen.Id("plan").Dot(fld.Name),
						)
					}
				})),
			),
		)
	f.Line()

	f.Func().
		Id("classifyChange").
		Params(
			jen.Id("state").Qual("github.com/hashicorp/terraform-plugin-framework/attr", "Value"),
			jen.Id("plan").Qual("github.com/hashicorp/terraform-plugin-framework/attr", "Value"),
		).
		Id("changeKind").
		Block(
			jen.If(jen.Id("plan").Dot("IsUnknown").Call()).Block(
				jen.Return(jen.Id("changeNone")),
			),
			jen.If(jen.Id("state").Dot("Equal").Call(jen.Id("plan"))).Block(
				jen.Return(jen.Id("changeNone")),
			),
			jen.If(jen.Id("plan").Dot("IsNull").Call()).Block(
				jen.Return(jen.Id("changeCleared")),
			),
			jen.Return(jen.Id("changeUpdated")),
		)
	f.Line()

	f.Func().
		Params(jen.Id("d").Id(diffTypeName)).
		Id("HasRemoteChanges").
		Params().
		Bool().
		Block(jen.Return(orChangedExpr(rootModel.Fields, isRemoteField, "IsChanged")))
	f.Line()

	f.Func().
		Params(jen.Id("d").Id(diffTypeName)).
		Id("RequiresTagApply").
		Params().
		Bool().
		Block(jen.Return(orChangedExpr(rootModel.Fields, isTagApplyField, "IsChanged")))

	var b bytes.Buffer
	if err := f.Render(&b); err != nil {
		return nil, fmt.Errorf("render diff file: %w", err)
	}

	return b.Bytes(), nil
}

func isRemoteField(f field) bool {
	if isTagApplyField(f) {
		return false
	}

	if f.Remote != nil {
		return *f.Remote
	}

	// Computed-only attributes are provider/AWS managed read-only fields.
	if f.Computed && !f.Optional && !f.Required {
		return false
	}

	return true
}

func isTagApplyField(f field) bool {
	return f.Tag == "tags" || f.Tag == "tags_all"
}

func orChangedExpr(fields []field, include func(field) bool, methodName string) *jen.Statement {
	included := make([]field, 0, len(fields))
	for _, fld := range fields {
		if include(fld) {
			included = append(included, fld)
		}
	}

	if len(included) == 0 {
		return jen.False()
	}

	expr := jen.Id("d").Dot(included[0].Name).Dot(methodName).Call()
	for _, fld := range included[1:] {
		expr = expr.Op("||").Id("d").Dot(fld.Name).Dot(methodName).Call()
	}
	return expr
}
