// Code generated by schema-to-artifacts. DO NOT EDIT.

package associate_application_entitlement

import types "github.com/hashicorp/terraform-plugin-framework/types"

type resourceModel struct {
	// A synthetic identifier for the association, composed of the stack name, entitlement name, and application
	// identifier. This value is managed by the provider and cannot be set manually.
	ID types.String `tfsdk:"id"`
	// The name of the AppStream stack in which the entitlement is defined. Changing this value forces the
	// association to be replaced.
	StackName types.String `tfsdk:"stack_name"`
	// The name of the entitlement to which the application is associated. Changing this value forces the association
	// to be replaced.
	EntitlementName types.String `tfsdk:"entitlement_name"`
	// The identifier of the AppStream application to associate with the entitlement. Changing this value forces the
	// association to be replaced.
	ApplicationIdentifier types.String `tfsdk:"application_identifier"`
}
