// Code generated by schema-to-artifacts. DO NOT EDIT.

package associate_fleet_stack

import types "github.com/hashicorp/terraform-plugin-framework/types"

type resourceModel struct {
	// A synthetic identifier for the association, composed of the fleet name and stack name. This value is managed
	// by the provider and cannot be set manually.
	ID types.String `tfsdk:"id"`
	// The name of the AppStream fleet to associate with the stack. Changing this value forces the association to be
	// replaced.
	FleetName types.String `tfsdk:"fleet_name"`
	// The name of the AppStream stack to associate with the fleet. Changing this value forces the association to be
	// replaced.
	StackName types.String `tfsdk:"stack_name"`
}
