// Code generated by schema-to-artifacts. DO NOT EDIT.

package export_image_task

import types "github.com/hashicorp/terraform-plugin-framework/types"

type dataSourceModel struct {
	// A synthetic identifier for the export image task, equal to the task ID.
	ID types.String `tfsdk:"id"`
	// The unique identifier of the export image task.
	TaskID types.String `tfsdk:"task_id"`
	// The Amazon Resource Name (ARN) of the AppStream Applications image being exported.
	ImageARN types.String `tfsdk:"image_arn"`
	// The name of the EC2 AMI created by the export image task.
	AmiName types.String `tfsdk:"ami_name"`
	// The description applied to the exported EC2 AMI, if set.
	AmiDescription types.String `tfsdk:"ami_description"`
	// The ID of the EC2 AMI created by the export image task. This attribute is only populated when the task
	// completes successfully.
	AmiID types.String `tfsdk:"ami_id"`
	// The current state of the export image task. Valid values are `EXPORTING`, `COMPLETED`, or `FAILED`.
	State types.String `tfsdk:"state"`
	// The timestamp when the export image task was created, in RFC 3339 format.
	CreatedDate types.String `tfsdk:"created_date"`
	// The tags applied to the exported EC2 AMI.
	TagSpecifications types.Map `tfsdk:"tag_specifications"`
	// Details about errors that occurred during the export process. This attribute is only populated when the task
	// state is `FAILED`.
	ErrorDetails types.Set `tfsdk:"error_details"`
}
type dataSourceModelErrorDetails struct {
	// The error code reported by AWS.
	ErrorCode types.String `tfsdk:"error_code"`
	// The human-readable error message reported by AWS.
	ErrorMessage types.String `tfsdk:"error_message"`
}
