// Code generated by schema-to-artifacts. DO NOT EDIT.

package sessions

import types "github.com/hashicorp/terraform-plugin-framework/types"

type dataSourceModel struct {
	// The name of the AppStream stack for which streaming sessions are listed.
	StackName types.String `tfsdk:"stack_name"`
	// The name of the AppStream fleet for which streaming sessions are listed.
	FleetName types.String `tfsdk:"fleet_name"`
	// The identifier of the user for whom streaming sessions are listed. If specified, `authentication_type` must
	// also be provided.
	UserID types.String `tfsdk:"user_id"`
	// The authentication method used by the user. Valid values are `API`, `SAML`, `USERPOOL`, or `AWS_AD`.
	AuthenticationType types.String `tfsdk:"authentication_type"`
	// The identifier of the streaming instance hosting the session.
	InstanceID types.String `tfsdk:"instance_id"`
	// The list of active streaming sessions that match the specified filters.
	Sessions types.Set `tfsdk:"sessions"`
}
type dataSourceModelSessionsNetworkAccessConfiguration struct {
	// The private IP address of the elastic network interface.
	EniPrivateIpAddress types.String `tfsdk:"eni_private_ip_address"`
	// The IPv6 addresses assigned to the elastic network interface.
	EniIpv6Addresses types.Set `tfsdk:"eni_ipv6_addresses"`
	// The identifier of the elastic network interface.
	EniID types.String `tfsdk:"eni_id"`
}
type dataSourceModelSessions struct {
	// The unique identifier of the streaming session.
	ID types.String `tfsdk:"id"`
	// The identifier of the user for whom the session was created.
	UserID types.String `tfsdk:"user_id"`
	// The name of the AppStream stack associated with the session.
	StackName types.String `tfsdk:"stack_name"`
	// The name of the AppStream fleet associated with the session.
	FleetName types.String `tfsdk:"fleet_name"`
	// The current state of the streaming session.
	State types.String `tfsdk:"state"`
	// Indicates whether the user is currently connected to the streaming session.
	ConnectionState types.String `tfsdk:"connection_state"`
	// The timestamp when the streaming session started, in RFC 3339 format.
	StartTime types.String `tfsdk:"start_time"`
	// The timestamp when the streaming session is scheduled to expire, in RFC 3339 format.
	MaxExpirationTime types.String `tfsdk:"max_expiration_time"`
	// The authentication method used for the session.
	AuthenticationType types.String `tfsdk:"authentication_type"`
	// The identifier of the instance hosting the streaming session.
	InstanceID types.String `tfsdk:"instance_id"`
	// Network details of the elastic network interface attached to the session.
	NetworkAccessConfiguration types.Object `tfsdk:"network_access_configuration"`
}
