// Code generated by schema-to-artifacts. DO NOT EDIT.

package user

import types "github.com/hashicorp/terraform-plugin-framework/types"

type dataSourceModel struct {
	// A synthetic identifier for the user, composed of the authentication type and user name in the format
	// `<authentication_type>|<user_name>`.
	ID types.String `tfsdk:"id"`
	// The authentication type associated with the user. Valid values are `API`, `SAML`, `USERPOOL`, or `AWS_AD`.
	AuthenticationType types.String `tfsdk:"authentication_type"`
	// The email address of the AppStream user. Email addresses are **case-sensitive**.
	UserName types.String `tfsdk:"user_name"`
	// The first (given) name of the user.
	FirstName types.String `tfsdk:"first_name"`
	// The last (family) name of the user.
	LastName types.String `tfsdk:"last_name"`
	// Indicates whether the user is enabled.
	Enabled types.Bool `tfsdk:"enabled"`
	// The status of the user as reported by AWS.
	Status types.String `tfsdk:"status"`
	// The Amazon Resource Name (ARN) of the AppStream user.
	ARN types.String `tfsdk:"arn"`
	// The timestamp when the user was created, in RFC 3339 format.
	CreatedTime types.String `tfsdk:"created_time"`
}
