// Code generated by schema-to-artifacts. DO NOT EDIT.

package user

import types "github.com/hashicorp/terraform-plugin-framework/types"

type resourceModel struct {
	// A synthetic identifier for the user, composed of the authentication type and user name. This value is managed
	// by the provider and cannot be set manually.
	ID types.String `tfsdk:"id"`
	// The authentication type used by the user. Changing this value forces the user to be replaced. Valid values are
	// `API`, `SAML`, `USERPOOL`, or `AWS_AD`.
	AuthenticationType types.String `tfsdk:"authentication_type"`
	// The email address of the AppStream user. Email addresses are **case-sensitive** and must exactly match during
	// login. Changing this value forces the user to be replaced.
	UserName types.String `tfsdk:"user_name"`
	// The first (given) name of the user.
	FirstName types.String `tfsdk:"first_name"`
	// The last (family) name of the user.
	LastName types.String `tfsdk:"last_name"`
	// Controls the welcome email sent to the user when the user is created. This setting is **write-only** and
	// applies only during creation. Valid values are `SUPPRESS` or `RESEND`. Changing this value forces the user to
	// be replaced.
	MessageAction types.String `tfsdk:"message_action"`
	// Specifies whether the user is enabled. Defaults to `true` if not explicitly set. Disabling a user prevents
	// login without deleting the user.
	Enabled types.Bool `tfsdk:"enabled"`
	// The status of the user as reported by AWS. This attribute is informational and cannot be modified.
	Status types.String `tfsdk:"status"`
	// The Amazon Resource Name (ARN) of the AppStream user.
	ARN types.String `tfsdk:"arn"`
	// The timestamp when the user was created, in RFC 3339 format.
	CreatedTime types.String `tfsdk:"created_time"`
}
