// Code generated by schema-to-artifacts. DO NOT EDIT.

package user

import attr "github.com/hashicorp/terraform-plugin-framework/attr"

// changeKind describes how a field transitions from state to plan.
type changeKind uint8

const (
	// changeNone means no actionable change for the field.
	changeNone changeKind = iota
	// changeUpdated means the field is set in plan and differs from state.
	changeUpdated
	// changeCleared means the field is explicitly set to null in plan.
	changeCleared
)

func (k changeKind) IsChanged() bool {
	return k != changeNone
}

func (k changeKind) IsUpdated() bool {
	return k == changeUpdated
}

func (k changeKind) IsCleared() bool {
	return k == changeCleared
}

type resourceDiff struct {
	ID                 changeKind
	AuthenticationType changeKind
	UserName           changeKind
	FirstName          changeKind
	LastName           changeKind
	MessageAction      changeKind
	Enabled            changeKind
	Status             changeKind
	ARN                changeKind
	CreatedTime        changeKind
}

func newResourceDiff(state resourceModel, plan resourceModel) resourceDiff {
	return resourceDiff{
		ARN:                classifyChange(state.ARN, plan.ARN),
		AuthenticationType: classifyChange(state.AuthenticationType, plan.AuthenticationType),
		CreatedTime:        classifyChange(state.CreatedTime, plan.CreatedTime),
		Enabled:            classifyChange(state.Enabled, plan.Enabled),
		FirstName:          classifyChange(state.FirstName, plan.FirstName),
		ID:                 classifyChange(state.ID, plan.ID),
		LastName:           classifyChange(state.LastName, plan.LastName),
		MessageAction:      classifyChange(state.MessageAction, plan.MessageAction),
		Status:             classifyChange(state.Status, plan.Status),
		UserName:           classifyChange(state.UserName, plan.UserName),
	}
}

func classifyChange(state attr.Value, plan attr.Value) changeKind {
	if plan.IsUnknown() {
		return changeNone
	}
	if state.Equal(plan) {
		return changeNone
	}
	if plan.IsNull() {
		return changeCleared
	}
	return changeUpdated
}

func (d resourceDiff) HasRemoteChanges() bool {
	return d.AuthenticationType.IsChanged() || d.UserName.IsChanged() || d.FirstName.IsChanged() || d.LastName.IsChanged() || d.MessageAction.IsChanged() || d.Enabled.IsChanged()
}

func (d resourceDiff) RequiresTagApply() bool {
	return false
}
