// Code generated by schema-to-artifacts. DO NOT EDIT.

package associate_image_builder_software

import types "github.com/hashicorp/terraform-plugin-framework/types"

type resourceModel struct {
	// A synthetic identifier for the association, equal to the image builder ARN. This value is managed by the
	// provider and cannot be set manually.
	ID types.String `tfsdk:"id"`
	// The ARN of the AppStream image builder to which the software is associated. Changing this value forces the
	// association to be replaced.
	ImageBuilderARN types.String `tfsdk:"image_builder_arn"`
	// A set of license-included software package names to associate with the AppStream image builder. Changes to
	// this set result in software being associated or disassociated accordingly.
	SoftwareNames types.Set `tfsdk:"software_names"`
	// Whether to trigger a software deployment to the image builder after associating the software. When set to
	// `true`, a deployment is started during apply. This setting does not track deployment progress or completion.
	Deploy types.Bool `tfsdk:"deploy"`
	// Per-software association status and deployment details as reported by AWS. This attribute is informational
	// only and does not affect Terraform lifecycle behavior.
	Associations types.Map `tfsdk:"associations"`
}
type resourceModelAssociationsDeploymentErrors struct {
	// The error code reported by AWS for the association.
	ErrorCode types.String `tfsdk:"error_code"`
	// The human-readable error message reported by AWS for the association.
	ErrorMessage types.String `tfsdk:"error_message"`
}
type resourceModelAssociations struct {
	// The deployment status of the license-included application for the image builder, as reported by AWS.
	Status types.String `tfsdk:"status"`
	// Informational list of error details for failed software deployments. These errors do not affect Terraform
	// lifecycle behavior.
	DeploymentErrors types.Set `tfsdk:"deployment_errors"`
}
