name: Tool AppStream Changelog Issues

on:
  pull_request:
    paths:
      - '.golangci.yaml'
      - '.github/workflows/tools-appstream-changelog-issues.yml'
      - 'tools/appstream-changelog-issues/**'
      - '!tools/appstream-changelog-issues/README.md'
  push:
    branches:
      - main
    paths:
      - '.golangci.yaml'
      - '.github/workflows/tools-appstream-changelog-issues.yml'
      - 'tools/appstream-changelog-issues/**'
      - '!tools/appstream-changelog-issues/README.md'
  workflow_dispatch:

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  test:
    name: AppStream Changelog Issues Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: tools/appstream-changelog-issues
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: 'tools/appstream-changelog-issues/go.mod'
          cache: true
      - name: Run Linters
        if: github.event_name != 'pull_request'
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
        with:
          version: latest
          working-directory: tools/appstream-changelog-issues
      - name: Install golangci-lint
        if: github.event_name == 'pull_request'
        run: go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest
      - name: Setup reviewdog
        if: github.event_name == 'pull_request'
        uses: reviewdog/action-setup@d8a7baabd7f3e8544ee4dbde3ee41d0011c3a93f # v1.5.0
        with:
          reviewdog_version: v0.21.0
      - name: Run Linters with reviewdog
        if: github.event_name == 'pull_request'
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          "$(go env GOPATH)/bin/golangci-lint" run \
            --output.text.path=stdout \
            --output.text.colors=false \
            ./... | \
          reviewdog \
            -f=golangci-lint \
            -name="golangci-lint-tool-appstream-changelog-issues" \
            -reporter=github-pr-review \
            -filter-mode=nofilter \
            -fail-level=error
      - run: go mod download
      - run: go test -v -cover -timeout 10m ./...
